// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pluralsh/kubernetes-agent/pkg/tool/redistool (interfaces: RpcApi)
//
// Generated by this command:
//
//	mockgen -typed -self_package github.com/pluralsh/kubernetes-agent/pkg/tool/redistool -destination mock_for_test.go -package redistool github.com/pluralsh/kubernetes-agent/pkg/tool/redistool RpcApi
//

// Package redistool is a generated GoMock package.
package redistool

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockRpcApi is a mock of RpcApi interface.
type MockRpcApi struct {
	ctrl     *gomock.Controller
	recorder *MockRpcApiMockRecorder
	isgomock struct{}
}

// MockRpcApiMockRecorder is the mock recorder for MockRpcApi.
type MockRpcApiMockRecorder struct {
	mock *MockRpcApi
}

// NewMockRpcApi creates a new mock instance.
func NewMockRpcApi(ctrl *gomock.Controller) *MockRpcApi {
	mock := &MockRpcApi{ctrl: ctrl}
	mock.recorder = &MockRpcApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRpcApi) EXPECT() *MockRpcApiMockRecorder {
	return m.recorder
}

// HandleProcessingError mocks base method.
func (m *MockRpcApi) HandleProcessingError(msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleProcessingError", msg, err)
}

// HandleProcessingError indicates an expected call of HandleProcessingError.
func (mr *MockRpcApiMockRecorder) HandleProcessingError(msg, err any) *MockRpcApiHandleProcessingErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProcessingError", reflect.TypeOf((*MockRpcApi)(nil).HandleProcessingError), msg, err)
	return &MockRpcApiHandleProcessingErrorCall{Call: call}
}

// MockRpcApiHandleProcessingErrorCall wrap *gomock.Call
type MockRpcApiHandleProcessingErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRpcApiHandleProcessingErrorCall) Return() *MockRpcApiHandleProcessingErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRpcApiHandleProcessingErrorCall) Do(f func(string, error)) *MockRpcApiHandleProcessingErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRpcApiHandleProcessingErrorCall) DoAndReturn(f func(string, error)) *MockRpcApiHandleProcessingErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Log mocks base method.
func (m *MockRpcApi) Log() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockRpcApiMockRecorder) Log() *MockRpcApiLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockRpcApi)(nil).Log))
	return &MockRpcApiLogCall{Call: call}
}

// MockRpcApiLogCall wrap *gomock.Call
type MockRpcApiLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRpcApiLogCall) Return(arg0 *zap.Logger) *MockRpcApiLogCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRpcApiLogCall) Do(f func() *zap.Logger) *MockRpcApiLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRpcApiLogCall) DoAndReturn(f func() *zap.Logger) *MockRpcApiLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RequestKey mocks base method.
func (m *MockRpcApi) RequestKey() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestKey")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// RequestKey indicates an expected call of RequestKey.
func (mr *MockRpcApiMockRecorder) RequestKey() *MockRpcApiRequestKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestKey", reflect.TypeOf((*MockRpcApi)(nil).RequestKey))
	return &MockRpcApiRequestKeyCall{Call: call}
}

// MockRpcApiRequestKeyCall wrap *gomock.Call
type MockRpcApiRequestKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRpcApiRequestKeyCall) Return(arg0 []byte) *MockRpcApiRequestKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRpcApiRequestKeyCall) Do(f func() []byte) *MockRpcApiRequestKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRpcApiRequestKeyCall) DoAndReturn(f func() []byte) *MockRpcApiRequestKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
