compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmMinimalAgeGate: 60

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": ">= 4.9.1 < 6"
      algoliasearch: ">= 4.9.1 < 6"
      search-insights: ">= 1 < 3"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": ">= 4.9.1 < 6"
      algoliasearch: ">= 4.9.1 < 6"
  "@apollo/sandbox@*":
    peerDependencies:
      graphql: ^15.7.2 || ^16.0.0
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": ">= 4.9.1 < 6"
      algoliasearch: ">= 4.9.1 < 6"
  "@nivo/annotations@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/arcs@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/axes@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/colors@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/core@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/geo@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/legends@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/line@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/pie@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/polar-axes@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/radial-bar@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/text@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/tooltip@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/treemap@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@nivo/voronoi@*":
    peerDependencies:
      react-dom: ^16.14 || ^17.0 || ^18.0 || ^19.0
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": ^16.8.0 || ^17.0.0 || ^18.0.0 || ^19.0.0
  babel-plugin-styled-components@*:
    peerDependencies:
      "@babel/core": ^7.0.0-0
  eslint-plugin-storybook@*:
    peerDependencies:
      typescript: ">=4.8.4 <6.1.0"
  storybook@*:
    peerDependencies:
      "@testing-library/dom": ">=7.21.4"
  vite-plugin-dts@*:
    peerDependencies:
      typescript: ">=4"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
