// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: pkg/module/agent_configuration/rpc/rpc.proto

// If you make any changes make sure you run: make regenerate-proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentConfiguration_GetConfiguration_FullMethodName = "/plural.agent.agent_configuration.rpc.AgentConfiguration/GetConfiguration"
)

// AgentConfigurationClient is the client API for AgentConfiguration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentConfigurationClient interface {
	// Get agentk configuration.
	GetConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigurationResponse], error)
}

type agentConfigurationClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentConfigurationClient(cc grpc.ClientConnInterface) AgentConfigurationClient {
	return &agentConfigurationClient{cc}
}

func (c *agentConfigurationClient) GetConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigurationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentConfiguration_ServiceDesc.Streams[0], AgentConfiguration_GetConfiguration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigurationRequest, ConfigurationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentConfiguration_GetConfigurationClient = grpc.ServerStreamingClient[ConfigurationResponse]

// AgentConfigurationServer is the server API for AgentConfiguration service.
// All implementations must embed UnimplementedAgentConfigurationServer
// for forward compatibility.
type AgentConfigurationServer interface {
	// Get agentk configuration.
	GetConfiguration(*ConfigurationRequest, grpc.ServerStreamingServer[ConfigurationResponse]) error
	mustEmbedUnimplementedAgentConfigurationServer()
}

// UnimplementedAgentConfigurationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentConfigurationServer struct{}

func (UnimplementedAgentConfigurationServer) GetConfiguration(*ConfigurationRequest, grpc.ServerStreamingServer[ConfigurationResponse]) error {
	return status.Error(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedAgentConfigurationServer) mustEmbedUnimplementedAgentConfigurationServer() {}
func (UnimplementedAgentConfigurationServer) testEmbeddedByValue()                            {}

// UnsafeAgentConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentConfigurationServer will
// result in compilation errors.
type UnsafeAgentConfigurationServer interface {
	mustEmbedUnimplementedAgentConfigurationServer()
}

func RegisterAgentConfigurationServer(s grpc.ServiceRegistrar, srv AgentConfigurationServer) {
	// If the following call panics, it indicates UnimplementedAgentConfigurationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentConfiguration_ServiceDesc, srv)
}

func _AgentConfiguration_GetConfiguration_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigurationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentConfigurationServer).GetConfiguration(m, &grpc.GenericServerStream[ConfigurationRequest, ConfigurationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentConfiguration_GetConfigurationServer = grpc.ServerStreamingServer[ConfigurationResponse]

// AgentConfiguration_ServiceDesc is the grpc.ServiceDesc for AgentConfiguration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentConfiguration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plural.agent.agent_configuration.rpc.AgentConfiguration",
	HandlerType: (*AgentConfigurationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetConfiguration",
			Handler:       _AgentConfiguration_GetConfiguration_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/module/agent_configuration/rpc/rpc.proto",
}
