{{ if .Values.postgres.create }}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: plural-hydra
  labels:
    app: postgres-hydra
    db: hydra
  {{ include "plural.labels" . | nindent 4 }}
spec:
  teamId: plural
  volume:
    size: {{ .Values.postgres.hydra.size }}
  numberOfInstances: 2
  {{ if .Values.postgres.hydra.resources }}
  resources:
  {{ mergeOverwrite .Values.postgres.default.resources .Values.postgres.hydra.resources | toYaml | nindent 4 }}
  {{ end }}
  users:
    hydra:  # database owner
    - superuser
    - createdb
  databases:
    hydra: hydra  # dbname: owner
  postgresql:
    version: "13"
  {{- with .Values.postgres.hydra.nodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgres.hydra.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-master
  labels:
    spilo-role: master
    {{ include "plural.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    spilo-role: master
    cluster-name: plural-hydra
{{ end }}