{{ if .Values.postgres.create }}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: plural-plural
  labels:
    app: postgres
    db: plural
  {{ include "plural.labels" . | nindent 4 }}
spec:
  teamId: plural
  volume:
    size: {{ .Values.postgres.plural.size }}
  numberOfInstances: 2
  {{ if .Values.postgres.plural.resources }}
  resources:
  {{ mergeOverwrite .Values.postgres.default.resources .Values.postgres.plural.resources | toYaml | nindent 4 }}
  {{ end }}
  users:
    plural:  # database owner
    - superuser
    - createdb
  databases:
    plural: plural  # dbname: owner
  postgresql:
    version: "13"
    parameters:
      max_connections: '101'
  {{- with .Values.postgres.plural.nodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgres.plural.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: plural-master
  labels:
    spilo-role: master
    {{ include "plural.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    spilo-role: master
    cluster-name: plural-plural
---
apiVersion: v1
kind: Service
metadata:
  name: plural-master-scrape
  labels:
    spilo-role: master
    {{ include "plural.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: plural-replica
  labels:
    spilo-role: replica
    {{ include "plural.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    spilo-role: replica
    cluster-name: plural-plural
{{ end }}