{:ok, _} = Application.ensure_all_started(:mimic)

Mimic.copy(Console.Commands.Plural)
Mimic.copy(Console.Commands.Command)
Mimic.copy(Console.Plural.Repositories)
Mimic.copy(Console.Plural.Incidents)
Mimic.copy(Console.Plural.Manifest)
Mimic.copy(Console.Plural.Context)
Mimic.copy(Console.Buffers.TokenAudit)
Mimic.copy(Console.Deployments.Git.Discovery)
Mimic.copy(Console.Deployments.Pipelines.Discovery)
Mimic.copy(Console.Deployments.Pipelines)
Mimic.copy(Console.Logs.Provider)
Mimic.copy(Console)
Mimic.copy(Kazan)
Mimic.copy(HTTPoison)
Mimic.copy(Kazan.Watcher)
Mimic.copy(Console.Kubernetes.PodExec)
Mimic.copy(Kazan.Server)
Mimic.copy(Console.Cached.Pod)
Mimic.copy(Console.Cached.Cluster)
Mimic.copy(Console.Cached.Secret)
Mimic.copy(File)
Mimic.copy(Console.Features)
Mimic.copy(Kube.Client)
Mimic.copy(Console.Cached.VPN)
Mimic.copy(Kube.Utils)
Mimic.copy(Console.Deployments.Clusters)
Mimic.copy(Console.Deployments.Git)
Mimic.copy(Phoenix.Channel.Server)
Mimic.copy(Tentacat)
Mimic.copy(Tentacat.Pulls)
Mimic.copy(Tentacat.Pulls.Files)
Mimic.copy(Tentacat.Pulls.Reviews)
Mimic.copy(Tentacat.App.Installations)
Mimic.copy(Tentacat.Organizations.Hooks)
Mimic.copy(Console.Deployments.Pr.Git)
Mimic.copy(Console.Deployments.Pr.Dispatcher)
Mimic.copy(Console.Deployments.Observer.Runner)
Mimic.copy(Console.AI.OpenAI)
Mimic.copy(ExAws)
Mimic.copy(Console.AI.Memoizer)
Mimic.copy(Console.AI.VectorStore)
Mimic.copy(Console.Mesh.Prometheus)
Mimic.copy(GRPC.Stub)
Mimic.copy(Cloudquery.CloudQuery.Stub)
Mimic.copy(Console.AI.Graph.Indexer.Sink)
Mimic.copy(Req)
Mimic.copy(Oidcc.Token)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Console.Repo, :manual)

{:ok, _} = Application.ensure_all_started(:ex_machina)
