{:ok, _} = Application.ensure_all_started(:mimic)

Mimic.copy(Console.Deployer)
Mimic.copy(Console.Storage.Git)
Mimic.copy(Console.Commands.Plural)
Mimic.copy(Console.Commands.Command)
Mimic.copy(Console.Plural.Repositories)
Mimic.copy(Console.Plural.Incidents)
Mimic.copy(Console.Plural.Manifest)
Mimic.copy(Console.Plural.Context)
Mimic.copy(Console.Buffers.TokenAudit)
Mimic.copy(Console.Deployments.Git.Discovery)
Mimic.copy(Console.Deployments.Pipelines.Discovery)
Mimic.copy(Console.Deployments.Pipelines)
Mimic.copy(Console)
Mimic.copy(Kazan)
Mimic.copy(HTTPoison)
Mimic.copy(Kazan.Watcher)
Mimic.copy(Console.Kubernetes.PodExec)
Mimic.copy(Kazan.Server)
Mimic.copy(Console.Cached.Pod)
Mimic.copy(Console.Cached.Cluster)
Mimic.copy(Console.Cached.Secret)
Mimic.copy(File)
Mimic.copy(Console.Features)
Mimic.copy(Kube.Client)
Mimic.copy(Console.Cached.VPN)
Mimic.copy(Kube.Utils)
Mimic.copy(Console.Deployments.Clusters)
Mimic.copy(Phoenix.Channel.Server)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Console.Repo, :manual)

{:ok, _} = Application.ensure_all_started(:ex_machina)
