fragment PolicyTiny on Policy {
  id
  name
  type
  description
  project {
    ...ProjectTiny
  }
  insertedAt
  updatedAt
}

fragment Policy on Policy {
  ...PolicyTiny
  policy
}

query Policies(
  $after: String
  $first: Int
  $before: String
  $last: Int
  $projectId: ID
  $q: String
) {
  policies(
    after: $after
    first: $first
    before: $before
    last: $last
    projectId: $projectId
    q: $q
  ) {
    pageInfo {
      ...PageInfo
    }
    edges {
      node {
        ...PolicyTiny
      }
    }
  }
}

query Policy($id: ID, $name: String) {
  policy(id: $id, name: $name) {
    ...Policy
  }
}

mutation CreatePolicy($attributes: PolicyAttributes!) {
  createPolicy(attributes: $attributes) {
    ...PolicyTiny
  }
}

mutation UpdatePolicy($id: ID!, $attributes: PolicyAttributes!) {
  updatePolicy(id: $id, attributes: $attributes) {
    ...PolicyTiny
  }
}

mutation DeletePolicy($id: ID!) {
  deletePolicy(id: $id) {
    ...PolicyTiny
  }
}

fragment BindingPolicyTiny on BindingPolicy {
  id
  type
  insertedAt
  updatedAt
  policy {
    ...PolicyTiny
  }
  bindPolicy {
    ...PolicyTiny
  }
}

query BindingPolicies(
  $after: String
  $first: Int
  $before: String
  $last: Int
) {
  bindingPolicies(
    after: $after
    first: $first
    before: $before
    last: $last
  ) {
    pageInfo {
      ...PageInfo
    }
    edges {
      node {
        ...BindingPolicyTiny
      }
    }
  }
}

mutation DeleteBindingPolicy($id: ID!) {
  deleteBindingPolicy(id: $id) {
    ...BindingPolicyTiny
  }
}
