fragment PolicyTiny on Policy {
  id
  name
  type
  description
  matchCount
  project {
    ...ProjectTiny
  }
  insertedAt
  updatedAt
}

fragment Policy on Policy {
  ...PolicyTiny
  policy
}

fragment PolicyWorkbenchAttachment on WorkbenchPolicy {
  id
  matches {
    regexes
  }
  workbench {
    id
    name
    description
  }
  insertedAt
  updatedAt
}

fragment PolicyStackAttachment on StackPolicy {
  id
  stack {
    id
    name
    type
  }
  insertedAt
  updatedAt
}

query Policies(
  $after: String
  $first: Int
  $before: String
  $last: Int
  $projectId: ID
  $q: String
) {
  policies(
    after: $after
    first: $first
    before: $before
    last: $last
    projectId: $projectId
    q: $q
  ) {
    pageInfo {
      ...PageInfo
    }
    edges {
      node {
        ...PolicyTiny
      }
    }
  }
}

query Policy($id: ID, $name: String) {
  policy(id: $id, name: $name) {
    ...Policy
  }
}

query PolicyAttachments(
  $id: ID!
  $first: Int
  $after: String
  $stackFirst: Int
  $stackAfter: String
) {
  policy(id: $id) {
    id
    workbenchPolicies(first: $first, after: $after) {
      pageInfo {
        ...PageInfo
      }
      edges {
        node {
          ...PolicyWorkbenchAttachment
        }
      }
    }
    stackPolicies(first: $stackFirst, after: $stackAfter) {
      pageInfo {
        ...PageInfo
      }
      edges {
        node {
          ...PolicyStackAttachment
        }
      }
    }
  }
}

mutation CreatePolicy($attributes: PolicyAttributes!) {
  createPolicy(attributes: $attributes) {
    ...PolicyTiny
  }
}

mutation UpdatePolicy($id: ID!, $attributes: PolicyAttributes!) {
  updatePolicy(id: $id, attributes: $attributes) {
    ...PolicyTiny
  }
}

mutation DeletePolicy($id: ID!) {
  deletePolicy(id: $id) {
    ...PolicyTiny
  }
}

fragment BindingPolicyTiny on BindingPolicy {
  id
  type
  insertedAt
  updatedAt
  policy {
    ...PolicyTiny
  }
  bindPolicy {
    ...PolicyTiny
  }
}

query BindingPolicies(
  $after: String
  $first: Int
  $before: String
  $last: Int
) {
  bindingPolicies(after: $after, first: $first, before: $before, last: $last) {
    pageInfo {
      ...PageInfo
    }
    edges {
      node {
        ...BindingPolicyTiny
      }
    }
  }
}

mutation DeleteBindingPolicy($id: ID!) {
  deleteBindingPolicy(id: $id) {
    ...BindingPolicyTiny
  }
}

fragment BindingPolicy on BindingPolicy {
  ...BindingPolicyTiny
  interval
  matches {
    workbench {
      regexes
    }
  }
}

query BindingPolicy($id: ID!) {
  bindingPolicy(id: $id) {
    ...BindingPolicy
  }
}

mutation CreateBindingPolicy($attributes: BindingPolicyAttributes!) {
  createBindingPolicy(attributes: $attributes) {
    ...BindingPolicyTiny
  }
}

mutation UpdateBindingPolicy(
  $id: ID!
  $attributes: BindingPolicyUpdateAttributes!
) {
  updateBindingPolicy(id: $id, attributes: $attributes) {
    ...BindingPolicyTiny
  }
}
