// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/kubernetes/typed/core/v1 (interfaces: CoreV1Interface,SecretInterface)
//
// Generated by this command:
//
//	mockgen -typed -destination core_v1.go -package mock_k8s k8s.io/client-go/kubernetes/typed/core/v1 CoreV1Interface,SecretInterface
//

// Package mock_k8s is a generated GoMock package.
package mock_k8s

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	v11 "k8s.io/client-go/applyconfigurations/core/v1"
	v12 "k8s.io/client-go/kubernetes/typed/core/v1"
	rest "k8s.io/client-go/rest"
)

// MockCoreV1Interface is a mock of CoreV1Interface interface.
type MockCoreV1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockCoreV1InterfaceMockRecorder
	isgomock struct{}
}

// MockCoreV1InterfaceMockRecorder is the mock recorder for MockCoreV1Interface.
type MockCoreV1InterfaceMockRecorder struct {
	mock *MockCoreV1Interface
}

// NewMockCoreV1Interface creates a new mock instance.
func NewMockCoreV1Interface(ctrl *gomock.Controller) *MockCoreV1Interface {
	mock := &MockCoreV1Interface{ctrl: ctrl}
	mock.recorder = &MockCoreV1InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreV1Interface) EXPECT() *MockCoreV1InterfaceMockRecorder {
	return m.recorder
}

// ComponentStatuses mocks base method.
func (m *MockCoreV1Interface) ComponentStatuses() v12.ComponentStatusInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComponentStatuses")
	ret0, _ := ret[0].(v12.ComponentStatusInterface)
	return ret0
}

// ComponentStatuses indicates an expected call of ComponentStatuses.
func (mr *MockCoreV1InterfaceMockRecorder) ComponentStatuses() *MockCoreV1InterfaceComponentStatusesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComponentStatuses", reflect.TypeOf((*MockCoreV1Interface)(nil).ComponentStatuses))
	return &MockCoreV1InterfaceComponentStatusesCall{Call: call}
}

// MockCoreV1InterfaceComponentStatusesCall wrap *gomock.Call
type MockCoreV1InterfaceComponentStatusesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceComponentStatusesCall) Return(arg0 v12.ComponentStatusInterface) *MockCoreV1InterfaceComponentStatusesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceComponentStatusesCall) Do(f func() v12.ComponentStatusInterface) *MockCoreV1InterfaceComponentStatusesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceComponentStatusesCall) DoAndReturn(f func() v12.ComponentStatusInterface) *MockCoreV1InterfaceComponentStatusesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfigMaps mocks base method.
func (m *MockCoreV1Interface) ConfigMaps(namespace string) v12.ConfigMapInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigMaps", namespace)
	ret0, _ := ret[0].(v12.ConfigMapInterface)
	return ret0
}

// ConfigMaps indicates an expected call of ConfigMaps.
func (mr *MockCoreV1InterfaceMockRecorder) ConfigMaps(namespace any) *MockCoreV1InterfaceConfigMapsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigMaps", reflect.TypeOf((*MockCoreV1Interface)(nil).ConfigMaps), namespace)
	return &MockCoreV1InterfaceConfigMapsCall{Call: call}
}

// MockCoreV1InterfaceConfigMapsCall wrap *gomock.Call
type MockCoreV1InterfaceConfigMapsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceConfigMapsCall) Return(arg0 v12.ConfigMapInterface) *MockCoreV1InterfaceConfigMapsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceConfigMapsCall) Do(f func(string) v12.ConfigMapInterface) *MockCoreV1InterfaceConfigMapsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceConfigMapsCall) DoAndReturn(f func(string) v12.ConfigMapInterface) *MockCoreV1InterfaceConfigMapsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Endpoints mocks base method.
func (m *MockCoreV1Interface) Endpoints(namespace string) v12.EndpointsInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoints", namespace)
	ret0, _ := ret[0].(v12.EndpointsInterface)
	return ret0
}

// Endpoints indicates an expected call of Endpoints.
func (mr *MockCoreV1InterfaceMockRecorder) Endpoints(namespace any) *MockCoreV1InterfaceEndpointsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoints", reflect.TypeOf((*MockCoreV1Interface)(nil).Endpoints), namespace)
	return &MockCoreV1InterfaceEndpointsCall{Call: call}
}

// MockCoreV1InterfaceEndpointsCall wrap *gomock.Call
type MockCoreV1InterfaceEndpointsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceEndpointsCall) Return(arg0 v12.EndpointsInterface) *MockCoreV1InterfaceEndpointsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceEndpointsCall) Do(f func(string) v12.EndpointsInterface) *MockCoreV1InterfaceEndpointsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceEndpointsCall) DoAndReturn(f func(string) v12.EndpointsInterface) *MockCoreV1InterfaceEndpointsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Events mocks base method.
func (m *MockCoreV1Interface) Events(namespace string) v12.EventInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", namespace)
	ret0, _ := ret[0].(v12.EventInterface)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockCoreV1InterfaceMockRecorder) Events(namespace any) *MockCoreV1InterfaceEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockCoreV1Interface)(nil).Events), namespace)
	return &MockCoreV1InterfaceEventsCall{Call: call}
}

// MockCoreV1InterfaceEventsCall wrap *gomock.Call
type MockCoreV1InterfaceEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceEventsCall) Return(arg0 v12.EventInterface) *MockCoreV1InterfaceEventsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceEventsCall) Do(f func(string) v12.EventInterface) *MockCoreV1InterfaceEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceEventsCall) DoAndReturn(f func(string) v12.EventInterface) *MockCoreV1InterfaceEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LimitRanges mocks base method.
func (m *MockCoreV1Interface) LimitRanges(namespace string) v12.LimitRangeInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LimitRanges", namespace)
	ret0, _ := ret[0].(v12.LimitRangeInterface)
	return ret0
}

// LimitRanges indicates an expected call of LimitRanges.
func (mr *MockCoreV1InterfaceMockRecorder) LimitRanges(namespace any) *MockCoreV1InterfaceLimitRangesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LimitRanges", reflect.TypeOf((*MockCoreV1Interface)(nil).LimitRanges), namespace)
	return &MockCoreV1InterfaceLimitRangesCall{Call: call}
}

// MockCoreV1InterfaceLimitRangesCall wrap *gomock.Call
type MockCoreV1InterfaceLimitRangesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceLimitRangesCall) Return(arg0 v12.LimitRangeInterface) *MockCoreV1InterfaceLimitRangesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceLimitRangesCall) Do(f func(string) v12.LimitRangeInterface) *MockCoreV1InterfaceLimitRangesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceLimitRangesCall) DoAndReturn(f func(string) v12.LimitRangeInterface) *MockCoreV1InterfaceLimitRangesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Namespaces mocks base method.
func (m *MockCoreV1Interface) Namespaces() v12.NamespaceInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespaces")
	ret0, _ := ret[0].(v12.NamespaceInterface)
	return ret0
}

// Namespaces indicates an expected call of Namespaces.
func (mr *MockCoreV1InterfaceMockRecorder) Namespaces() *MockCoreV1InterfaceNamespacesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespaces", reflect.TypeOf((*MockCoreV1Interface)(nil).Namespaces))
	return &MockCoreV1InterfaceNamespacesCall{Call: call}
}

// MockCoreV1InterfaceNamespacesCall wrap *gomock.Call
type MockCoreV1InterfaceNamespacesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceNamespacesCall) Return(arg0 v12.NamespaceInterface) *MockCoreV1InterfaceNamespacesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceNamespacesCall) Do(f func() v12.NamespaceInterface) *MockCoreV1InterfaceNamespacesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceNamespacesCall) DoAndReturn(f func() v12.NamespaceInterface) *MockCoreV1InterfaceNamespacesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Nodes mocks base method.
func (m *MockCoreV1Interface) Nodes() v12.NodeInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nodes")
	ret0, _ := ret[0].(v12.NodeInterface)
	return ret0
}

// Nodes indicates an expected call of Nodes.
func (mr *MockCoreV1InterfaceMockRecorder) Nodes() *MockCoreV1InterfaceNodesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nodes", reflect.TypeOf((*MockCoreV1Interface)(nil).Nodes))
	return &MockCoreV1InterfaceNodesCall{Call: call}
}

// MockCoreV1InterfaceNodesCall wrap *gomock.Call
type MockCoreV1InterfaceNodesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceNodesCall) Return(arg0 v12.NodeInterface) *MockCoreV1InterfaceNodesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceNodesCall) Do(f func() v12.NodeInterface) *MockCoreV1InterfaceNodesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceNodesCall) DoAndReturn(f func() v12.NodeInterface) *MockCoreV1InterfaceNodesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PersistentVolumeClaims mocks base method.
func (m *MockCoreV1Interface) PersistentVolumeClaims(namespace string) v12.PersistentVolumeClaimInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistentVolumeClaims", namespace)
	ret0, _ := ret[0].(v12.PersistentVolumeClaimInterface)
	return ret0
}

// PersistentVolumeClaims indicates an expected call of PersistentVolumeClaims.
func (mr *MockCoreV1InterfaceMockRecorder) PersistentVolumeClaims(namespace any) *MockCoreV1InterfacePersistentVolumeClaimsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistentVolumeClaims", reflect.TypeOf((*MockCoreV1Interface)(nil).PersistentVolumeClaims), namespace)
	return &MockCoreV1InterfacePersistentVolumeClaimsCall{Call: call}
}

// MockCoreV1InterfacePersistentVolumeClaimsCall wrap *gomock.Call
type MockCoreV1InterfacePersistentVolumeClaimsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfacePersistentVolumeClaimsCall) Return(arg0 v12.PersistentVolumeClaimInterface) *MockCoreV1InterfacePersistentVolumeClaimsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfacePersistentVolumeClaimsCall) Do(f func(string) v12.PersistentVolumeClaimInterface) *MockCoreV1InterfacePersistentVolumeClaimsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfacePersistentVolumeClaimsCall) DoAndReturn(f func(string) v12.PersistentVolumeClaimInterface) *MockCoreV1InterfacePersistentVolumeClaimsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PersistentVolumes mocks base method.
func (m *MockCoreV1Interface) PersistentVolumes() v12.PersistentVolumeInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistentVolumes")
	ret0, _ := ret[0].(v12.PersistentVolumeInterface)
	return ret0
}

// PersistentVolumes indicates an expected call of PersistentVolumes.
func (mr *MockCoreV1InterfaceMockRecorder) PersistentVolumes() *MockCoreV1InterfacePersistentVolumesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistentVolumes", reflect.TypeOf((*MockCoreV1Interface)(nil).PersistentVolumes))
	return &MockCoreV1InterfacePersistentVolumesCall{Call: call}
}

// MockCoreV1InterfacePersistentVolumesCall wrap *gomock.Call
type MockCoreV1InterfacePersistentVolumesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfacePersistentVolumesCall) Return(arg0 v12.PersistentVolumeInterface) *MockCoreV1InterfacePersistentVolumesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfacePersistentVolumesCall) Do(f func() v12.PersistentVolumeInterface) *MockCoreV1InterfacePersistentVolumesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfacePersistentVolumesCall) DoAndReturn(f func() v12.PersistentVolumeInterface) *MockCoreV1InterfacePersistentVolumesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PodTemplates mocks base method.
func (m *MockCoreV1Interface) PodTemplates(namespace string) v12.PodTemplateInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PodTemplates", namespace)
	ret0, _ := ret[0].(v12.PodTemplateInterface)
	return ret0
}

// PodTemplates indicates an expected call of PodTemplates.
func (mr *MockCoreV1InterfaceMockRecorder) PodTemplates(namespace any) *MockCoreV1InterfacePodTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PodTemplates", reflect.TypeOf((*MockCoreV1Interface)(nil).PodTemplates), namespace)
	return &MockCoreV1InterfacePodTemplatesCall{Call: call}
}

// MockCoreV1InterfacePodTemplatesCall wrap *gomock.Call
type MockCoreV1InterfacePodTemplatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfacePodTemplatesCall) Return(arg0 v12.PodTemplateInterface) *MockCoreV1InterfacePodTemplatesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfacePodTemplatesCall) Do(f func(string) v12.PodTemplateInterface) *MockCoreV1InterfacePodTemplatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfacePodTemplatesCall) DoAndReturn(f func(string) v12.PodTemplateInterface) *MockCoreV1InterfacePodTemplatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Pods mocks base method.
func (m *MockCoreV1Interface) Pods(namespace string) v12.PodInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pods", namespace)
	ret0, _ := ret[0].(v12.PodInterface)
	return ret0
}

// Pods indicates an expected call of Pods.
func (mr *MockCoreV1InterfaceMockRecorder) Pods(namespace any) *MockCoreV1InterfacePodsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pods", reflect.TypeOf((*MockCoreV1Interface)(nil).Pods), namespace)
	return &MockCoreV1InterfacePodsCall{Call: call}
}

// MockCoreV1InterfacePodsCall wrap *gomock.Call
type MockCoreV1InterfacePodsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfacePodsCall) Return(arg0 v12.PodInterface) *MockCoreV1InterfacePodsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfacePodsCall) Do(f func(string) v12.PodInterface) *MockCoreV1InterfacePodsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfacePodsCall) DoAndReturn(f func(string) v12.PodInterface) *MockCoreV1InterfacePodsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RESTClient mocks base method.
func (m *MockCoreV1Interface) RESTClient() rest.Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RESTClient")
	ret0, _ := ret[0].(rest.Interface)
	return ret0
}

// RESTClient indicates an expected call of RESTClient.
func (mr *MockCoreV1InterfaceMockRecorder) RESTClient() *MockCoreV1InterfaceRESTClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RESTClient", reflect.TypeOf((*MockCoreV1Interface)(nil).RESTClient))
	return &MockCoreV1InterfaceRESTClientCall{Call: call}
}

// MockCoreV1InterfaceRESTClientCall wrap *gomock.Call
type MockCoreV1InterfaceRESTClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceRESTClientCall) Return(arg0 rest.Interface) *MockCoreV1InterfaceRESTClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceRESTClientCall) Do(f func() rest.Interface) *MockCoreV1InterfaceRESTClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceRESTClientCall) DoAndReturn(f func() rest.Interface) *MockCoreV1InterfaceRESTClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplicationControllers mocks base method.
func (m *MockCoreV1Interface) ReplicationControllers(namespace string) v12.ReplicationControllerInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicationControllers", namespace)
	ret0, _ := ret[0].(v12.ReplicationControllerInterface)
	return ret0
}

// ReplicationControllers indicates an expected call of ReplicationControllers.
func (mr *MockCoreV1InterfaceMockRecorder) ReplicationControllers(namespace any) *MockCoreV1InterfaceReplicationControllersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicationControllers", reflect.TypeOf((*MockCoreV1Interface)(nil).ReplicationControllers), namespace)
	return &MockCoreV1InterfaceReplicationControllersCall{Call: call}
}

// MockCoreV1InterfaceReplicationControllersCall wrap *gomock.Call
type MockCoreV1InterfaceReplicationControllersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceReplicationControllersCall) Return(arg0 v12.ReplicationControllerInterface) *MockCoreV1InterfaceReplicationControllersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceReplicationControllersCall) Do(f func(string) v12.ReplicationControllerInterface) *MockCoreV1InterfaceReplicationControllersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceReplicationControllersCall) DoAndReturn(f func(string) v12.ReplicationControllerInterface) *MockCoreV1InterfaceReplicationControllersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResourceQuotas mocks base method.
func (m *MockCoreV1Interface) ResourceQuotas(namespace string) v12.ResourceQuotaInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceQuotas", namespace)
	ret0, _ := ret[0].(v12.ResourceQuotaInterface)
	return ret0
}

// ResourceQuotas indicates an expected call of ResourceQuotas.
func (mr *MockCoreV1InterfaceMockRecorder) ResourceQuotas(namespace any) *MockCoreV1InterfaceResourceQuotasCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceQuotas", reflect.TypeOf((*MockCoreV1Interface)(nil).ResourceQuotas), namespace)
	return &MockCoreV1InterfaceResourceQuotasCall{Call: call}
}

// MockCoreV1InterfaceResourceQuotasCall wrap *gomock.Call
type MockCoreV1InterfaceResourceQuotasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceResourceQuotasCall) Return(arg0 v12.ResourceQuotaInterface) *MockCoreV1InterfaceResourceQuotasCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceResourceQuotasCall) Do(f func(string) v12.ResourceQuotaInterface) *MockCoreV1InterfaceResourceQuotasCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceResourceQuotasCall) DoAndReturn(f func(string) v12.ResourceQuotaInterface) *MockCoreV1InterfaceResourceQuotasCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Secrets mocks base method.
func (m *MockCoreV1Interface) Secrets(namespace string) v12.SecretInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secrets", namespace)
	ret0, _ := ret[0].(v12.SecretInterface)
	return ret0
}

// Secrets indicates an expected call of Secrets.
func (mr *MockCoreV1InterfaceMockRecorder) Secrets(namespace any) *MockCoreV1InterfaceSecretsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secrets", reflect.TypeOf((*MockCoreV1Interface)(nil).Secrets), namespace)
	return &MockCoreV1InterfaceSecretsCall{Call: call}
}

// MockCoreV1InterfaceSecretsCall wrap *gomock.Call
type MockCoreV1InterfaceSecretsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceSecretsCall) Return(arg0 v12.SecretInterface) *MockCoreV1InterfaceSecretsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceSecretsCall) Do(f func(string) v12.SecretInterface) *MockCoreV1InterfaceSecretsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceSecretsCall) DoAndReturn(f func(string) v12.SecretInterface) *MockCoreV1InterfaceSecretsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ServiceAccounts mocks base method.
func (m *MockCoreV1Interface) ServiceAccounts(namespace string) v12.ServiceAccountInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAccounts", namespace)
	ret0, _ := ret[0].(v12.ServiceAccountInterface)
	return ret0
}

// ServiceAccounts indicates an expected call of ServiceAccounts.
func (mr *MockCoreV1InterfaceMockRecorder) ServiceAccounts(namespace any) *MockCoreV1InterfaceServiceAccountsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAccounts", reflect.TypeOf((*MockCoreV1Interface)(nil).ServiceAccounts), namespace)
	return &MockCoreV1InterfaceServiceAccountsCall{Call: call}
}

// MockCoreV1InterfaceServiceAccountsCall wrap *gomock.Call
type MockCoreV1InterfaceServiceAccountsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceServiceAccountsCall) Return(arg0 v12.ServiceAccountInterface) *MockCoreV1InterfaceServiceAccountsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceServiceAccountsCall) Do(f func(string) v12.ServiceAccountInterface) *MockCoreV1InterfaceServiceAccountsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceServiceAccountsCall) DoAndReturn(f func(string) v12.ServiceAccountInterface) *MockCoreV1InterfaceServiceAccountsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Services mocks base method.
func (m *MockCoreV1Interface) Services(namespace string) v12.ServiceInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Services", namespace)
	ret0, _ := ret[0].(v12.ServiceInterface)
	return ret0
}

// Services indicates an expected call of Services.
func (mr *MockCoreV1InterfaceMockRecorder) Services(namespace any) *MockCoreV1InterfaceServicesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Services", reflect.TypeOf((*MockCoreV1Interface)(nil).Services), namespace)
	return &MockCoreV1InterfaceServicesCall{Call: call}
}

// MockCoreV1InterfaceServicesCall wrap *gomock.Call
type MockCoreV1InterfaceServicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCoreV1InterfaceServicesCall) Return(arg0 v12.ServiceInterface) *MockCoreV1InterfaceServicesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCoreV1InterfaceServicesCall) Do(f func(string) v12.ServiceInterface) *MockCoreV1InterfaceServicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCoreV1InterfaceServicesCall) DoAndReturn(f func(string) v12.ServiceInterface) *MockCoreV1InterfaceServicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSecretInterface is a mock of SecretInterface interface.
type MockSecretInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSecretInterfaceMockRecorder
	isgomock struct{}
}

// MockSecretInterfaceMockRecorder is the mock recorder for MockSecretInterface.
type MockSecretInterfaceMockRecorder struct {
	mock *MockSecretInterface
}

// NewMockSecretInterface creates a new mock instance.
func NewMockSecretInterface(ctrl *gomock.Controller) *MockSecretInterface {
	mock := &MockSecretInterface{ctrl: ctrl}
	mock.recorder = &MockSecretInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretInterface) EXPECT() *MockSecretInterfaceMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockSecretInterface) Apply(ctx context.Context, secret *v11.SecretApplyConfiguration, opts v10.ApplyOptions) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, secret, opts)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockSecretInterfaceMockRecorder) Apply(ctx, secret, opts any) *MockSecretInterfaceApplyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockSecretInterface)(nil).Apply), ctx, secret, opts)
	return &MockSecretInterfaceApplyCall{Call: call}
}

// MockSecretInterfaceApplyCall wrap *gomock.Call
type MockSecretInterfaceApplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceApplyCall) Return(result *v1.Secret, err error) *MockSecretInterfaceApplyCall {
	c.Call = c.Call.Return(result, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceApplyCall) Do(f func(context.Context, *v11.SecretApplyConfiguration, v10.ApplyOptions) (*v1.Secret, error)) *MockSecretInterfaceApplyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceApplyCall) DoAndReturn(f func(context.Context, *v11.SecretApplyConfiguration, v10.ApplyOptions) (*v1.Secret, error)) *MockSecretInterfaceApplyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockSecretInterface) Create(ctx context.Context, secret *v1.Secret, opts v10.CreateOptions) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, secret, opts)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSecretInterfaceMockRecorder) Create(ctx, secret, opts any) *MockSecretInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecretInterface)(nil).Create), ctx, secret, opts)
	return &MockSecretInterfaceCreateCall{Call: call}
}

// MockSecretInterfaceCreateCall wrap *gomock.Call
type MockSecretInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceCreateCall) Return(arg0 *v1.Secret, arg1 error) *MockSecretInterfaceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceCreateCall) Do(f func(context.Context, *v1.Secret, v10.CreateOptions) (*v1.Secret, error)) *MockSecretInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceCreateCall) DoAndReturn(f func(context.Context, *v1.Secret, v10.CreateOptions) (*v1.Secret, error)) *MockSecretInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockSecretInterface) Delete(ctx context.Context, name string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretInterfaceMockRecorder) Delete(ctx, name, opts any) *MockSecretInterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecretInterface)(nil).Delete), ctx, name, opts)
	return &MockSecretInterfaceDeleteCall{Call: call}
}

// MockSecretInterfaceDeleteCall wrap *gomock.Call
type MockSecretInterfaceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceDeleteCall) Return(arg0 error) *MockSecretInterfaceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceDeleteCall) Do(f func(context.Context, string, v10.DeleteOptions) error) *MockSecretInterfaceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceDeleteCall) DoAndReturn(f func(context.Context, string, v10.DeleteOptions) error) *MockSecretInterfaceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCollection mocks base method.
func (m *MockSecretInterface) DeleteCollection(ctx context.Context, opts v10.DeleteOptions, listOpts v10.ListOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, opts, listOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockSecretInterfaceMockRecorder) DeleteCollection(ctx, opts, listOpts any) *MockSecretInterfaceDeleteCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockSecretInterface)(nil).DeleteCollection), ctx, opts, listOpts)
	return &MockSecretInterfaceDeleteCollectionCall{Call: call}
}

// MockSecretInterfaceDeleteCollectionCall wrap *gomock.Call
type MockSecretInterfaceDeleteCollectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceDeleteCollectionCall) Return(arg0 error) *MockSecretInterfaceDeleteCollectionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceDeleteCollectionCall) Do(f func(context.Context, v10.DeleteOptions, v10.ListOptions) error) *MockSecretInterfaceDeleteCollectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceDeleteCollectionCall) DoAndReturn(f func(context.Context, v10.DeleteOptions, v10.ListOptions) error) *MockSecretInterfaceDeleteCollectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockSecretInterface) Get(ctx context.Context, name string, opts v10.GetOptions) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name, opts)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecretInterfaceMockRecorder) Get(ctx, name, opts any) *MockSecretInterfaceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSecretInterface)(nil).Get), ctx, name, opts)
	return &MockSecretInterfaceGetCall{Call: call}
}

// MockSecretInterfaceGetCall wrap *gomock.Call
type MockSecretInterfaceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceGetCall) Return(arg0 *v1.Secret, arg1 error) *MockSecretInterfaceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceGetCall) Do(f func(context.Context, string, v10.GetOptions) (*v1.Secret, error)) *MockSecretInterfaceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceGetCall) DoAndReturn(f func(context.Context, string, v10.GetOptions) (*v1.Secret, error)) *MockSecretInterfaceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockSecretInterface) List(ctx context.Context, opts v10.ListOptions) (*v1.SecretList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(*v1.SecretList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretInterfaceMockRecorder) List(ctx, opts any) *MockSecretInterfaceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretInterface)(nil).List), ctx, opts)
	return &MockSecretInterfaceListCall{Call: call}
}

// MockSecretInterfaceListCall wrap *gomock.Call
type MockSecretInterfaceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceListCall) Return(arg0 *v1.SecretList, arg1 error) *MockSecretInterfaceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceListCall) Do(f func(context.Context, v10.ListOptions) (*v1.SecretList, error)) *MockSecretInterfaceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceListCall) DoAndReturn(f func(context.Context, v10.ListOptions) (*v1.SecretList, error)) *MockSecretInterfaceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Patch mocks base method.
func (m *MockSecretInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v10.PatchOptions, subresources ...string) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, pt, data, opts}
	for _, a := range subresources {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockSecretInterfaceMockRecorder) Patch(ctx, name, pt, data, opts any, subresources ...any) *MockSecretInterfacePatchCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, pt, data, opts}, subresources...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockSecretInterface)(nil).Patch), varargs...)
	return &MockSecretInterfacePatchCall{Call: call}
}

// MockSecretInterfacePatchCall wrap *gomock.Call
type MockSecretInterfacePatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfacePatchCall) Return(result *v1.Secret, err error) *MockSecretInterfacePatchCall {
	c.Call = c.Call.Return(result, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfacePatchCall) Do(f func(context.Context, string, types.PatchType, []byte, v10.PatchOptions, ...string) (*v1.Secret, error)) *MockSecretInterfacePatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfacePatchCall) DoAndReturn(f func(context.Context, string, types.PatchType, []byte, v10.PatchOptions, ...string) (*v1.Secret, error)) *MockSecretInterfacePatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockSecretInterface) Update(ctx context.Context, secret *v1.Secret, opts v10.UpdateOptions) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, secret, opts)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSecretInterfaceMockRecorder) Update(ctx, secret, opts any) *MockSecretInterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSecretInterface)(nil).Update), ctx, secret, opts)
	return &MockSecretInterfaceUpdateCall{Call: call}
}

// MockSecretInterfaceUpdateCall wrap *gomock.Call
type MockSecretInterfaceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceUpdateCall) Return(arg0 *v1.Secret, arg1 error) *MockSecretInterfaceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceUpdateCall) Do(f func(context.Context, *v1.Secret, v10.UpdateOptions) (*v1.Secret, error)) *MockSecretInterfaceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceUpdateCall) DoAndReturn(f func(context.Context, *v1.Secret, v10.UpdateOptions) (*v1.Secret, error)) *MockSecretInterfaceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Watch mocks base method.
func (m *MockSecretInterface) Watch(ctx context.Context, opts v10.ListOptions) (watch.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, opts)
	ret0, _ := ret[0].(watch.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockSecretInterfaceMockRecorder) Watch(ctx, opts any) *MockSecretInterfaceWatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockSecretInterface)(nil).Watch), ctx, opts)
	return &MockSecretInterfaceWatchCall{Call: call}
}

// MockSecretInterfaceWatchCall wrap *gomock.Call
type MockSecretInterfaceWatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretInterfaceWatchCall) Return(arg0 watch.Interface, arg1 error) *MockSecretInterfaceWatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretInterfaceWatchCall) Do(f func(context.Context, v10.ListOptions) (watch.Interface, error)) *MockSecretInterfaceWatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretInterfaceWatchCall) DoAndReturn(f func(context.Context, v10.ListOptions) (watch.Interface, error)) *MockSecretInterfaceWatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
