// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pluralsh/kubernetes-agent/pkg/module/modshared (interfaces: RpcApi,Api)
//
// Generated by this command:
//
//	mockgen -typed -destination api.go -package mock_modshared github.com/pluralsh/kubernetes-agent/pkg/module/modshared RpcApi,Api
//

// Package mock_modshared is a generated GoMock package.
package mock_modshared

import (
	context "context"
	reflect "reflect"

	retry "github.com/pluralsh/kubernetes-agent/pkg/tool/retry"
	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockRpcApi is a mock of RpcApi interface.
type MockRpcApi struct {
	ctrl     *gomock.Controller
	recorder *MockRpcApiMockRecorder
	isgomock struct{}
}

// MockRpcApiMockRecorder is the mock recorder for MockRpcApi.
type MockRpcApiMockRecorder struct {
	mock *MockRpcApi
}

// NewMockRpcApi creates a new mock instance.
func NewMockRpcApi(ctrl *gomock.Controller) *MockRpcApi {
	mock := &MockRpcApi{ctrl: ctrl}
	mock.recorder = &MockRpcApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRpcApi) EXPECT() *MockRpcApiMockRecorder {
	return m.recorder
}

// HandleIoError mocks base method.
func (m *MockRpcApi) HandleIoError(log *zap.Logger, msg string, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleIoError", log, msg, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleIoError indicates an expected call of HandleIoError.
func (mr *MockRpcApiMockRecorder) HandleIoError(log, msg, err any) *MockRpcApiHandleIoErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleIoError", reflect.TypeOf((*MockRpcApi)(nil).HandleIoError), log, msg, err)
	return &MockRpcApiHandleIoErrorCall{Call: call}
}

// MockRpcApiHandleIoErrorCall wrap *gomock.Call
type MockRpcApiHandleIoErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRpcApiHandleIoErrorCall) Return(arg0 error) *MockRpcApiHandleIoErrorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRpcApiHandleIoErrorCall) Do(f func(*zap.Logger, string, error) error) *MockRpcApiHandleIoErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRpcApiHandleIoErrorCall) DoAndReturn(f func(*zap.Logger, string, error) error) *MockRpcApiHandleIoErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HandleProcessingError mocks base method.
func (m *MockRpcApi) HandleProcessingError(log *zap.Logger, agentId int64, msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleProcessingError", log, agentId, msg, err)
}

// HandleProcessingError indicates an expected call of HandleProcessingError.
func (mr *MockRpcApiMockRecorder) HandleProcessingError(log, agentId, msg, err any) *MockRpcApiHandleProcessingErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProcessingError", reflect.TypeOf((*MockRpcApi)(nil).HandleProcessingError), log, agentId, msg, err)
	return &MockRpcApiHandleProcessingErrorCall{Call: call}
}

// MockRpcApiHandleProcessingErrorCall wrap *gomock.Call
type MockRpcApiHandleProcessingErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRpcApiHandleProcessingErrorCall) Return() *MockRpcApiHandleProcessingErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRpcApiHandleProcessingErrorCall) Do(f func(*zap.Logger, int64, string, error)) *MockRpcApiHandleProcessingErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRpcApiHandleProcessingErrorCall) DoAndReturn(f func(*zap.Logger, int64, string, error)) *MockRpcApiHandleProcessingErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Log mocks base method.
func (m *MockRpcApi) Log() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockRpcApiMockRecorder) Log() *MockRpcApiLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockRpcApi)(nil).Log))
	return &MockRpcApiLogCall{Call: call}
}

// MockRpcApiLogCall wrap *gomock.Call
type MockRpcApiLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRpcApiLogCall) Return(arg0 *zap.Logger) *MockRpcApiLogCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRpcApiLogCall) Do(f func() *zap.Logger) *MockRpcApiLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRpcApiLogCall) DoAndReturn(f func() *zap.Logger) *MockRpcApiLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PollWithBackoff mocks base method.
func (m *MockRpcApi) PollWithBackoff(cfg retry.PollConfig, f retry.PollWithBackoffFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollWithBackoff", cfg, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// PollWithBackoff indicates an expected call of PollWithBackoff.
func (mr *MockRpcApiMockRecorder) PollWithBackoff(cfg, f any) *MockRpcApiPollWithBackoffCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollWithBackoff", reflect.TypeOf((*MockRpcApi)(nil).PollWithBackoff), cfg, f)
	return &MockRpcApiPollWithBackoffCall{Call: call}
}

// MockRpcApiPollWithBackoffCall wrap *gomock.Call
type MockRpcApiPollWithBackoffCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRpcApiPollWithBackoffCall) Return(arg0 error) *MockRpcApiPollWithBackoffCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRpcApiPollWithBackoffCall) Do(f func(retry.PollConfig, retry.PollWithBackoffFunc) error) *MockRpcApiPollWithBackoffCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRpcApiPollWithBackoffCall) DoAndReturn(f func(retry.PollConfig, retry.PollWithBackoffFunc) error) *MockRpcApiPollWithBackoffCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockApi is a mock of Api interface.
type MockApi struct {
	ctrl     *gomock.Controller
	recorder *MockApiMockRecorder
	isgomock struct{}
}

// MockApiMockRecorder is the mock recorder for MockApi.
type MockApiMockRecorder struct {
	mock *MockApi
}

// NewMockApi creates a new mock instance.
func NewMockApi(ctrl *gomock.Controller) *MockApi {
	mock := &MockApi{ctrl: ctrl}
	mock.recorder = &MockApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApi) EXPECT() *MockApiMockRecorder {
	return m.recorder
}

// HandleProcessingError mocks base method.
func (m *MockApi) HandleProcessingError(ctx context.Context, log *zap.Logger, agentId int64, msg string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleProcessingError", ctx, log, agentId, msg, err)
}

// HandleProcessingError indicates an expected call of HandleProcessingError.
func (mr *MockApiMockRecorder) HandleProcessingError(ctx, log, agentId, msg, err any) *MockApiHandleProcessingErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProcessingError", reflect.TypeOf((*MockApi)(nil).HandleProcessingError), ctx, log, agentId, msg, err)
	return &MockApiHandleProcessingErrorCall{Call: call}
}

// MockApiHandleProcessingErrorCall wrap *gomock.Call
type MockApiHandleProcessingErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiHandleProcessingErrorCall) Return() *MockApiHandleProcessingErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiHandleProcessingErrorCall) Do(f func(context.Context, *zap.Logger, int64, string, error)) *MockApiHandleProcessingErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiHandleProcessingErrorCall) DoAndReturn(f func(context.Context, *zap.Logger, int64, string, error)) *MockApiHandleProcessingErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
