defmodule Console.Deployments.Pr.Impl.BitBucketDatacenterTest do
  use Console.DataCase, async: true
  use Mimic

  alias Console.Deployments.Pr.Impl.BitBucketDatacenter
  alias Console.Deployments.Pr.Review
  alias Console.Schema.{PrAutomation, PullRequest, ScmConnection}

  describe "pr/1" do
    test "parses Bitbucket Data Center pullRequest payloads" do
      payload = %{
        "eventKey" => "pr:opened",
        "pullRequest" => %{
          "id" => 42,
          "title" => "Add deployment retries",
          "description" => "Plural Flow: deploy-flow",
          "state" => "OPEN",
          "fromRef" => %{"displayId" => "feature/retries"},
          "toRef" => %{"displayId" => "main"},
          "links" => %{
            "self" => [
              %{"href" => "https://bitbucket.example.com/projects/PROJ/repos/repo/pull-requests/42"}
            ]
          }
        }
      }

      assert {:ok, url, attrs} = BitBucketDatacenter.pr(payload)
      assert url == "https://bitbucket.example.com/projects/PROJ/repos/repo/pull-requests/42"
      assert attrs.status == :open
      assert attrs.ref == "feature/retries"
      assert attrs.base == "main"
      assert attrs.title == "Add deployment retries"
      assert attrs.body == "Plural Flow: deploy-flow"
    end

    test "maps merged state from Data Center payloads" do
      payload = %{
        "eventKey" => "pr:merged",
        "pullRequest" => %{
          "title" => "Merge PR",
          "description" => "done",
          "state" => "MERGED",
          "fromRef" => %{"displayId" => "feature/retries"},
          "toRef" => %{"displayId" => "main"},
          "links" => %{
            "self" => [
              %{"href" => "https://bitbucket.example.com/projects/PROJ/repos/repo/pull-requests/43"}
            ]
          }
        }
      }

      assert {:ok, _url, attrs} = BitBucketDatacenter.pr(payload)
      assert attrs.status == :merged
    end
  end

  describe "create/4" do
    test "creates a pull request using the Bitbucket Data Center 9.x request shape" do
      connection = %ScmConnection{
        type: :bitbucket_datacenter,
        api_url: "https://bitbucket.example.com/rest/api/latest",
        token: "token"
      }

      pr = %PrAutomation{
        branch: "main",
        connection: connection,
        identifier: "PROJ/repo",
        ignore_templates: true,
        title: "Agent change",
        message: "Generated by the agent"
      }

      expect(Req, :post, fn url, opts ->
        assert url ==
                 "https://bitbucket.example.com/rest/api/1.0/projects/PROJ/repos/repo/pull-requests"

        assert_bearer_auth(opts)

        assert Jason.decode!(opts[:body]) == %{
                 "title" => "Agent change",
                 "description" => "Generated by the agent",
                 "fromRef" => %{
                   "id" => "refs/heads/agent/change"
                 },
                 "toRef" => %{
                   "id" => "refs/heads/main"
                 }
               }

        response(%{"id" => 42})
      end)

      assert {:ok, %{url: url}} = BitBucketDatacenter.create(pr, "agent/change", %{})

      assert url ==
               "https://bitbucket.example.com/projects/PROJ/repos/repo/pull-requests/42"
    end
  end

  describe "agent_review/3" do
    test "uses the documented effective-diff anchor" do
      connection = %ScmConnection{
        type: :bitbucket_datacenter,
        api_url: "https://bitbucket.example.com",
        username: "user",
        token: "token"
      }

      url = "https://bitbucket.example.com/projects/PROJ/repos/repo/pull-requests/42"
      pr = %PullRequest{url: url}

      review =
        Review.new(%{
          url: url,
          confidence: :b,
          summary: "Safe refactor",
          confidence_comment: "One finding needs attention.",
          comments: [
            %{
              filename: "lib/example.ex",
              line: 12,
              title: "Unhandled error",
              body: "Handle this error.",
              priority: :p1
            }
          ]
        })

      expect(Req, :post, 2, fn _, opts ->
        assert_bearer_auth(opts)
        body = Jason.decode!(opts[:body])

        case body["anchor"] do
          nil ->
            response(%{"id" => 10})

          anchor ->
            assert anchor == %{
                     "diffType" => "EFFECTIVE",
                     "fileType" => "TO",
                     "line" => 12,
                     "lineType" => "ADDED",
                     "path" => "lib/example.ex"
                   }

            response(%{"id" => 11})
        end
      end)

      assert {:ok, "10"} = BitBucketDatacenter.agent_review(connection, pr, review)
    end

    test "uses bearer authentication when the connection has no username" do
      connection = %ScmConnection{
        type: :bitbucket_datacenter,
        api_url: "https://bitbucket.example.com",
        token: "token"
      }

      pr = %PullRequest{
        url: "https://bitbucket.example.com/projects/PROJ/repos/repo/pull-requests/42"
      }

      expect(Req, :post, fn _, opts ->
        assert_bearer_auth(opts)
        response(%{"id" => 10})
      end)

      assert {:ok, "10"} = BitBucketDatacenter.review(connection, pr, "Review body")
    end
  end

  describe "commit_status/5" do
    test "publishes cancelled runs as cancelled build statuses" do
      connection = %ScmConnection{
        type: :bitbucket_datacenter,
        api_url: "https://bitbucket.example.com",
        username: "user",
        token: "token"
      }

      pr = %PullRequest{
        url: "https://bitbucket.example.com/projects/PROJ/repos/repo/pull-requests/42"
      }

      expect(Req, :post, fn url, opts ->
        assert_bearer_auth(opts)
        assert url ==
                 "https://bitbucket.example.com/rest/api/latest/projects/PROJ/repos/repo/commits/head-sha/builds"

        assert Jason.decode!(opts[:body]) == %{
                 "key" => "check-42",
                 "state" => "CANCELLED",
                 "url" => "https://console.example.com/ai/agent-runs/run-id",
                 "name" => "Plural: Agent review",
                 "description" => "Plural agent review"
               }

        response(%{})
      end)

      assert {:ok, "check-42"} =
               BitBucketDatacenter.commit_status(
                 connection,
                 pr,
                 "check-42",
                 :cancelled,
                 %{
                   sha: "head-sha",
                   url: "https://console.example.com/ai/agent-runs/run-id",
                   name: "Plural: Agent review",
                   description: "Plural agent review"
                 }
               )
    end
  end

  defp assert_bearer_auth(opts) do
    assert {"Authorization", "Bearer token"} in opts[:headers]
    refute Enum.any?(opts[:headers], fn
             {"Authorization", "Basic " <> _} -> true
             _ -> false
           end)
  end

  defp response(body) do
    {:ok, %Req.Response{status: 201, body: Jason.encode!(body)}}
  end
end
