import {
  Card,
  EmptyState,
  Flex,
  Markdown,
  useSetBreadcrumbs,
} from '@pluralsh/design-system'
import { useMemo } from 'react'
import { useOutletContext } from 'react-router-dom'
import styled from 'styled-components'

import { CaptionP } from 'components/utils/typography/Text'
import { dateFormat } from 'utils/date'
import { StackOutletContextT, getBreadcrumbs } from '../Stacks'

export function StackInsights() {
  const { stack } = useOutletContext() as StackOutletContextT

  useSetBreadcrumbs(
    useMemo(
      () => [...getBreadcrumbs(stack.id, stack.name), { label: 'insights' }],
      [stack]
    )
  )
  return (
    <Flex
      direction="column"
      gap="medium"
      overflow="hidden"
    >
      <Flex
        justify="flex-end"
        gap="small"
      >
        <CaptionP
          css={{ width: 'max-content' }}
          $color="text-xlight"
        >
          {stack.insight?.updatedAt &&
            `Last updated ${dateFormat(stack.insight?.updatedAt)}`}
        </CaptionP>
        {/* TODO: Add refresh button here */}
      </Flex>
      <InsightWrapperCard>
        {stack.insight?.text ? (
          <Markdown text={stack.insight.text} />
        ) : (
          <EmptyState
            message="No insights available"
            description="Insights are generated by Plural AI when the stack is in a failing state."
          />
        )}
      </InsightWrapperCard>
    </Flex>
  )
}

const InsightWrapperCard = styled(Card)(({ theme }) => ({
  padding: theme.spacing.medium,
  overflow: 'auto',
}))
