import {
  Button,
  Card,
  EmptyState,
  Flex,
  Markdown,
  ReloadIcon,
  useSetBreadcrumbs,
} from '@pluralsh/design-system'
import { useMemo } from 'react'
import { useOutletContext } from 'react-router-dom'
import styled from 'styled-components'

import { CaptionP } from 'components/utils/typography/Text'
import { StackOutletContextT, getBreadcrumbs } from '../Stacks'
import moment from 'moment/moment'

export function StackInsights() {
  const { stack, refetch, loading } = useOutletContext() as StackOutletContextT

  useSetBreadcrumbs(
    useMemo(
      () => [...getBreadcrumbs(stack.id, stack.name), { label: 'insights' }],
      [stack]
    )
  )
  return (
    <Flex
      direction="column"
      gap="medium"
      overflow="hidden"
    >
      <Flex
        justify="flex-end"
        gap="small"
      >
        <CaptionP
          css={{ width: 'max-content' }}
          $color="text-xlight"
        >
          {stack.insight?.updatedAt &&
            `Last updated ${moment(stack.insight?.updatedAt).fromNow()}`}
        </CaptionP>
        <Button
          floating
          startIcon={<ReloadIcon />}
          onClick={() => refetch?.()}
          loading={loading}
        >
          Refresh insights
        </Button>
      </Flex>
      <InsightDisplay text={stack.insight?.text} />
    </Flex>
  )
}

export const InsightDisplay = ({ text }: { text: Nullable<string> }) => {
  return (
    <InsightWrapperCardSC>
      {text ? (
        <Markdown text={text} />
      ) : (
        <EmptyState
          message="No insights available"
          description="Insights are generated by Plural AI when triggered by a failing state."
        />
      )}
    </InsightWrapperCardSC>
  )
}

const InsightWrapperCardSC = styled(Card)(({ theme }) => ({
  padding: theme.spacing.medium,
  overflow: 'auto',
}))
