apiVersion: v2
name: kas
description: k8s agent server
version: 0.3.2
appVersion: "0.2.2"
dependencies:
  - name: redis
    version: 24.0.0
    repository: file://../../chart-dependencies/redis
    condition: redis.enabled
