global:
  additionalVolumes: ~
  additionalVolumeMounts: ~

consoleUrl: ""

nameOverride: ""

fullnameOverride: ""

podAnnotations: {}
podLabels: {}

priorityClassName: ""

extraEnv: []

extraArgs: []

nodeSelector: {}

affinity: {}

tolerations: []

initContainers: []
