// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: pkg/gitlab/gitlab.proto

// If you make any changes make sure you run: make regenerate-proto

package gitlab

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientError) Reset() {
	*x = ClientError{}
	mi := &file_pkg_gitlab_gitlab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientError) ProtoMessage() {}

func (x *ClientError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gitlab_gitlab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientError.ProtoReflect.Descriptor instead.
func (*ClientError) Descriptor() ([]byte, []int) {
	return file_pkg_gitlab_gitlab_proto_rawDescGZIP(), []int{0}
}

func (x *ClientError) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ClientError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ClientError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// see https://gitlab.com/gitlab-org/gitlab/blob/2864126a72835bd0b29f670ffc36828014850f5f/lib/api/helpers.rb#L534-534
type DefaultApiError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultApiError) Reset() {
	*x = DefaultApiError{}
	mi := &file_pkg_gitlab_gitlab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultApiError) ProtoMessage() {}

func (x *DefaultApiError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gitlab_gitlab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultApiError.ProtoReflect.Descriptor instead.
func (*DefaultApiError) Descriptor() ([]byte, []int) {
	return file_pkg_gitlab_gitlab_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultApiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_gitlab_gitlab_proto protoreflect.FileDescriptor

const file_pkg_gitlab_gitlab_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/gitlab/gitlab.proto\x12\x13plural.agent.gitlab\"Z\n" +
	"\vClientError\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"+\n" +
	"\x0fDefaultApiError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB1Z/github.com/pluralsh/kubernetes-agent/pkg/gitlabb\x06proto3"

var (
	file_pkg_gitlab_gitlab_proto_rawDescOnce sync.Once
	file_pkg_gitlab_gitlab_proto_rawDescData []byte
)

func file_pkg_gitlab_gitlab_proto_rawDescGZIP() []byte {
	file_pkg_gitlab_gitlab_proto_rawDescOnce.Do(func() {
		file_pkg_gitlab_gitlab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_gitlab_gitlab_proto_rawDesc), len(file_pkg_gitlab_gitlab_proto_rawDesc)))
	})
	return file_pkg_gitlab_gitlab_proto_rawDescData
}

var file_pkg_gitlab_gitlab_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_gitlab_gitlab_proto_goTypes = []any{
	(*ClientError)(nil),     // 0: plural.agent.gitlab.ClientError
	(*DefaultApiError)(nil), // 1: plural.agent.gitlab.DefaultApiError
}
var file_pkg_gitlab_gitlab_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_gitlab_gitlab_proto_init() }
func file_pkg_gitlab_gitlab_proto_init() {
	if File_pkg_gitlab_gitlab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_gitlab_gitlab_proto_rawDesc), len(file_pkg_gitlab_gitlab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_gitlab_gitlab_proto_goTypes,
		DependencyIndexes: file_pkg_gitlab_gitlab_proto_depIdxs,
		MessageInfos:      file_pkg_gitlab_gitlab_proto_msgTypes,
	}.Build()
	File_pkg_gitlab_gitlab_proto = out.File
	file_pkg_gitlab_gitlab_proto_goTypes = nil
	file_pkg_gitlab_gitlab_proto_depIdxs = nil
}
