import { Card, EmptyState, Markdown } from '@pluralsh/design-system'
import styled from 'styled-components'

export const InsightDisplay = ({ text }: { text: Nullable<string> }) => {
  return (
    <InsightWrapperCardSC>
      {text ? (
        <Markdown text={text} />
      ) : (
        <EmptyState
          message="No insights available"
          description="Insights are generated by Plural AI when triggered by a failing state."
        />
      )}
    </InsightWrapperCardSC>
  )
}

const InsightWrapperCardSC = styled(Card)(({ theme }) => ({
  flexGrow: 1,
  padding: theme.spacing.medium,
  overflow: 'auto',
}))
