defmodule Console.GraphQl.Deployments.Observability do
  use Console.GraphQl.Schema.Base
  alias Console.GraphQl.Resolvers.{Deployments}
  alias Console.Schema.{ObservabilityWebhook, ObservabilityProvider, Alert, Monitor}

  ecto_enum :observability_provider_type, ObservabilityProvider.Type
  ecto_enum :observability_webhook_type,  ObservabilityWebhook.Type
  ecto_enum :alert_severity,              Alert.Severity
  ecto_enum :alert_state,                 Alert.State
  ecto_enum :monitor_type,                Monitor.Type
  ecto_enum :monitor_aggregate,           Monitor.Aggregate
  ecto_enum :monitor_operator,            Monitor.Operator

  @desc "Attributes for creating or updating an external observability provider"
  input_object :observability_provider_attributes do
    field :type, non_null(:observability_provider_type),
      description: "Type of observability provider (for example Datadog or New Relic)"

    field :name, non_null(:string),
      description: "Human‑readable name for this provider; must be unique per deployment"

    field :credentials, non_null(:observability_provider_credentials_attributes),
      description: "Provider‑specific credentials required to authenticate API calls"
  end

  @desc "Provider‑specific credential blocks; only one provider key should be populated"
  input_object :observability_provider_credentials_attributes do
    field :datadog, :datadog_credentials_attributes,
      description: "Datadog API credentials"

    field :newrelic, :new_relic_credentials_attributes,
      description: "New Relic API credentials"
  end

  @desc "Datadog API credentials"
  input_object :datadog_credentials_attributes do
    field :api_key, non_null(:string),
      description: "Datadog API key with access to query metrics and logs"

    field :app_key, non_null(:string),
      description: "Datadog application key used alongside the API key"
  end

  @desc "New Relic API credentials"
  input_object :new_relic_credentials_attributes do
    field :api_key, non_null(:string),
      description: "New Relic user or ingest API key with access to query telemetry"
  end

  @desc "Attributes linking a metric in an external provider to this deployment"
  input_object :observable_metric_attributes do
    field :identifier, non_null(:string),
      description: "Provider‑specific metric identifier (for example metric name or query ID)"

    field :provider_id, non_null(:id),
      description: "ID of the observability provider that owns this metric"
  end

  @desc "Attributes used to create or update an observability monitor"
  input_object :monitor_attributes do
    field :service_id, non_null(:id),
      description: "ID of the service deployment this monitor should be attached to"

    field :workbench_id, :id, description: "ID of the workbench this monitor should be attached to"

    field :name, non_null(:string),
      description: "Short name used to identify this monitor"

    field :description, :string,
      description: "Optional free‑form description of what this monitor is checking"

    field :alert_template, :string,
      description: "Optional template used when rendering alert messages for this monitor"

    field :severity, non_null(:alert_severity),
      description: "Severity level applied to alerts generated by this monitor"

    field :type, non_null(:monitor_type),
      description: "Monitor type (currently log‑based only)"

    field :evaluation_cron, non_null(:string),
      description: "Cron schedule defining when the monitor is evaluated (for example */5 * * * *)"

    field :query, non_null(:monitor_query_attributes),
      description: "Underlying query configuration used to fetch data for this monitor"

    field :threshold, non_null(:monitor_threshold_attributes),
      description: "Threshold configuration that determines when the monitor should fire"
  end

  @desc "Threshold configuration used to decide when a monitor should fire"
  input_object :monitor_threshold_attributes do
    field :aggregate, non_null(:monitor_aggregate),
      description: "Aggregation function applied over the result set (max, min, avg)"

    field :value, non_null(:float),
      description: "Numeric value the aggregated metric must cross to trigger the alert"
  end

  @desc "Wrapper for the underlying query definition for a monitor"
  input_object :monitor_query_attributes do
    field :log, non_null(:monitor_log_query_attributes),
      description: "Log query used when the monitor type is log‑based"
  end

  @desc "Log query configuration for a monitor"
  input_object :monitor_log_query_attributes do
    field :query, non_null(:string),
      description: "Log query string passed through to the underlying log provider"

    field :bucket_size, non_null(:string),
      description: "Time bucket size (for example 5m) used when aggregating log results"

    field :duration, :string,
      description: "Lookback duration for the log query (for example 1h, 10m, 30s)"

    field :operator, :monitor_operator,
      description: "Operator to use when combining multiple log queries"

    field :facets, list_of(:monitor_facet_attributes),
      description: "Optional key/value facets applied as additional filters on the log query"
  end

  @desc "Key/value facet used to further filter log queries"
  input_object :monitor_facet_attributes do
    field :key, non_null(:string),
      description: "Facet key (for example kubernetes namespace or pod label name)"

    field :value, non_null(:string),
      description: "Facet value to match for the given key"
  end

  @desc "Attributes used to persist a human‑authored resolution for an alert"
  input_object :alert_resolution_attributes do
    field :resolution, non_null(:string),
      description: "Free‑form description of how the alert was resolved or triaged"
  end

  @desc "input data to persist a webhook receiver for an observability provider like grafana or datadog"
  input_object :observability_webhook_attributes do
    field :type, non_null(:observability_webhook_type),
      description: "Type of webhook endpoint (for example Grafana alerting)"

    field :name, non_null(:string),
      description: "Unique name used to reference this webhook"

    field :secret, :string,
      description: "Optional shared secret used to validate incoming webhook payloads"
  end

  @desc "Configuration for an external observability provider such as Datadog or New Relic"
  object :observability_provider do
    field :id, non_null(:id),
      description: "Stable identifier for this observability provider"

    field :type, non_null(:observability_provider_type),
      description: "Type of provider (for example :datadog or :newrelic)"

    field :name, non_null(:string),
      description: "Human‑readable name for this provider"

    timestamps()
  end

  @desc "A metric exposed by an external observability provider and referenced by the console"
  object :observable_metric do
    field :id, non_null(:id),
      description: "Stable identifier for this observable metric"

    field :identifier, non_null(:string),
      description: "Provider‑specific metric identifier (for example Prometheus metric name)"

    field :provider, :observability_provider,
      description: "Observability provider that owns this metric",
      resolve: dataloader(Deployments)

    timestamps()
  end

  @desc "A webhook receiver for an observability provider like grafana or datadog"
  object :observability_webhook do
    field :id, non_null(:id),
      description: "Stable identifier for this webhook"

    field :type, non_null(:observability_webhook_type),
      description: "Type of observability webhook (for example :grafana)"

    field :name, non_null(:string),
      description: "Human‑readable name for this webhook"

    field :url, non_null(:string),
      description: "the url for this specific webhook",
      resolve: fn hook, _, _ -> {:ok, ObservabilityWebhook.url(hook)} end

    timestamps()
  end

  @desc "A monitor defines a recurring check over observability data that can raise alerts"
  object :monitor do
    field :id, non_null(:id),
      description: "Stable identifier for this monitor"

    field :name, non_null(:string),
      description: "Short name used to identify this monitor"

    field :description, :string,
      description: "Optional free‑form description of what this monitor is checking"

    field :alert_template, :string,
      description: "Optional template used when rendering alert messages for this monitor"

    field :severity, non_null(:alert_severity),
      description: "Severity level for alerts generated by this monitor"

    field :state, :alert_state, description: "Current state of the monitor (either firing or resolved)"

    field :type, non_null(:monitor_type),
      description: "Monitor type (currently log‑based only)"

    field :evaluation_cron, non_null(:string),
      description: "Cron schedule defining when the monitor is evaluated"

    field :next_run_at, :datetime,
      description: "Next scheduled time this monitor will be evaluated, if any"

    field :query, non_null(:monitor_query),
      description: "Underlying query configuration used to fetch data for this monitor"

    field :threshold, non_null(:monitor_threshold),
      description: "Threshold configuration that determines when the monitor should fire"

    field :service, :service_deployment,
      description: "The service deployment this monitor is attached to",
      resolve: dataloader(Deployments)

    field :workbench, :workbench,
      description: "The workbench this monitor is attached to",
      resolve: dataloader(Deployments)

    timestamps()
  end

  @desc "A single key/value facet used when filtering log queries"
  object :monitor_facet do
    field :key, non_null(:string),
      description: "Facet key (for example kubernetes label or field name)"

    field :value, non_null(:string),
      description: "Facet value to match for the given key"
  end

  @desc "Log‑level query parameters for a monitor"
  object :monitor_log_query do
    field :query, non_null(:string),
      description: "Log query string passed through to the underlying log provider"

    field :duration, :string,
      description: "Lookback duration for the log query (for example 1h, 10m, 30s)"

    field :operator, :monitor_operator,
      description: "Operator to use for evaluating multi word log queries"

    field :bucket_size, non_null(:string),
      description: "Time bucket size (for example 5m) used when aggregating log results"

    field :facets, list_of(:monitor_facet),
      description: "Optional list of facets used to filter log results"
  end

  @desc "Wrapper object for all query types used by a monitor"
  object :monitor_query do
    field :log, non_null(:monitor_log_query),
      description: "Log query configuration used by this monitor"
  end

  @desc "Threshold configuration defining when a monitor should fire alerts"
  object :monitor_threshold do
    field :aggregate, non_null(:monitor_aggregate),
      description: "Aggregation function applied over the result set (max, min, avg)"

    field :value, non_null(:float),
      description: "Numeric value the aggregated metric must cross to trigger the alert"
  end

  @desc "An individual alert raised from an observability provider or monitor"
  object :alert do
    field :id, non_null(:id),
      description: "Stable identifier for this alert"

    field :type, non_null(:observability_webhook_type),
      description: "Origin of this alert (for example :grafana)"

    field :severity, non_null(:alert_severity),
      description: "Severity level of this alert as reported by the provider"

    field :state, non_null(:alert_state),
      description: "Current state of the alert (for example firing or resolved)"

    field :title, :string,
      description: "Short title summarizing the alert condition"

    field :message, :string,
      description: "Detailed message or summary supplied by the provider"

    field :fingerprint, :string,
      description: "Provider‑defined fingerprint used to deduplicate alert instances"

    field :annotations, :map,
      description: "Arbitrary key/value annotations attached to this alert"

    field :url, :string,
      description: "Link back to the originating dashboard or alert view in the provider"

    field :tags, list_of(:tag),
      resolve: dataloader(Deployments),
      description: "Key/value tags associated with this alert, often used for filtering clusters"

    field :resolution, :alert_resolution,
      resolve: dataloader(Deployments),
      description: "The human‑authored resolution for this alert, if one exists"

    field :insight, :ai_insight,
      resolve: dataloader(Deployments),
      description: "An AI‑generated insight explaining the current state of this alert"

    field :cluster, :cluster,
      resolve: dataloader(Deployments),
      description: "The cluster this alert was associated with"

    field :service, :service,
      resolve: dataloader(Deployments),
      description: "The service this alert was associated with"

    field :project, :project,
      resolve: dataloader(Deployments),
      description: "The project this alert was associated with"

    field :flow, :flow,
      resolve: dataloader(Deployments),
      description: "The flow this alert was associated with"

    field :workbench, :workbench,
      resolve: dataloader(Deployments),
      description: "The workbench this alert was associated with"

    field :timeseries, :alert_timeseries,
      description: "Time series metrics and threshold used when this alert was evaluated"

    timestamps()
  end

  @desc "A human‑authored explanation of how an alert was resolved"
  object :alert_resolution do
    field :id, non_null(:id),
      description: "Stable identifier for this alert resolution"

    field :resolution, non_null(:string),
      description: "The resolution text explaining how the alert was handled"

    field :alert, :alert,
      resolve: dataloader(Deployments),
      description: "The alert this resolution was associated with"

    timestamps()
  end

  @desc "A representation of the metrics to render a utilization heat map"
  object :utilization_heat_map do
    field :cpu, list_of(:metric_point_response),
      description: "CPU utilization data points grouped by time bucket"

    field :memory, list_of(:metric_point_response),
      description: "Memory utilization data points grouped by time bucket"
  end

  @desc "Aggregated metrics for a Kubernetes controller and its pods"
  object :kubernetes_controller_metrics do
    field :cpu, list_of(:metric_response),
      description: "CPU usage metrics for the controller"

    field :mem, list_of(:metric_response),
      description: "Memory usage metrics for the controller"

    field :pod_cpu, list_of(:metric_response),
      description: "CPU usage metrics for pods managed by this controller"

    field :pod_mem, list_of(:metric_response),
      description: "Memory usage metrics for pods managed by this controller"
  end

  @desc "Time series data associated with an alert evaluation"
  object :alert_timeseries do
    field :threshold, :float,
      description: "Threshold value used when evaluating this alert over time"

    field :metrics, list_of(:metric_result),
      description: "Ordered list of metric points collected while evaluating this alert"
  end

  connection node_type: :observability_provider
  connection node_type: :observability_webhook
  connection node_type: :alert
  connection node_type: :monitor

  @desc "Queries for fetching observability providers and webhooks"
  object :observability_provider_queries do
    field :observability_provider, :observability_provider do
      @desc "Fetch a single observability provider by ID or name"
      middleware Authenticated
      arg :id, :id, description: "ID of the observability provider to fetch"
      arg :name, :string, description: "Name of the observability provider to fetch"

      resolve &Deployments.get_observability_provider/2
    end

    connection field :observability_providers, node_type: :observability_provider do
      @desc "List observability providers visible to the current user"
      middleware Authenticated

      resolve &Deployments.list_observability_providers/2
    end

    field :observability_webhook, :observability_webhook do
      @desc "Fetch a single observability webhook by ID or name"
      middleware Authenticated
      arg :id, :id, description: "ID of the observability webhook to fetch"
      arg :name, :string, description: "Name of the observability webhook to fetch"

      resolve &Deployments.get_observability_webhook/2
    end

    connection field :observability_webhooks, node_type: :observability_webhook do
      @desc "List observability webhooks visible to the current user"
      middleware Authenticated

      resolve &Deployments.list_observability_webhooks/2
    end

    field :monitor, :monitor do
      @desc "Fetch a single monitor by ID"
      middleware Authenticated
      arg :id, non_null(:id), description: "ID of the monitor to fetch"

      resolve &Deployments.get_monitor/2
    end
  end

  @desc "Mutations for managing observability providers, webhooks, alerts, and monitors"
  object :observability_provider_mutations do
    field :upsert_observability_provider, :observability_provider do
      @desc "Create or update an observability provider configuration"
      middleware Authenticated
      arg :attributes, non_null(:observability_provider_attributes),
        description: "Attributes used to create or update the observability provider"

      resolve &Deployments.upsert_observability_provider/2
    end

    field :delete_observability_provider, :observability_provider do
      @desc "Delete an observability provider by ID"
      middleware Authenticated
      arg :id, non_null(:id),
        description: "ID of the observability provider to delete"

      resolve &Deployments.delete_observability_provider/2
    end

    field :upsert_observability_webhook, :observability_webhook do
      @desc "Create or update an observability webhook"
      middleware Authenticated
      arg :attributes, non_null(:observability_webhook_attributes),
        description: "Attributes used to create or update the observability webhook"

      resolve &Deployments.upsert_observability_webhook/2
    end

    field :delete_observability_webhook, :observability_webhook do
      @desc "Delete an observability webhook by ID"
      middleware Authenticated
      arg :id, non_null(:id),
        description: "ID of the observability webhook to delete"

      resolve &Deployments.delete_observability_webhook/2
    end

    field :create_alert_resolution, :alert_resolution do
      @desc "Create or update the resolution associated with an alert"
      middleware Authenticated
      arg :id, non_null(:id),
        description: "ID of the alert to attach the resolution to"

      arg :attributes, non_null(:alert_resolution_attributes),
        description: "Attributes describing how the alert was resolved"

      resolve &Deployments.create_alert_resolution/2
    end

    field :create_monitor, :monitor do
      @desc "Create a new monitor attached to a service deployment"
      middleware Authenticated
      arg :attributes, non_null(:monitor_attributes),
        description: "Attributes used to create the monitor"

      resolve &Deployments.create_monitor/2
    end

    field :update_monitor, :monitor do
      @desc "Update an existing monitor"
      middleware Authenticated
      arg :id, non_null(:id),
        description: "ID of the monitor to update"

      arg :attributes, non_null(:monitor_attributes),
        description: "Attributes used to update the monitor"

      resolve &Deployments.update_monitor/2
    end

    field :delete_monitor, :monitor do
      @desc "Delete an existing monitor"
      middleware Authenticated
      arg :id, non_null(:id),
        description: "ID of the monitor to delete"

      resolve &Deployments.delete_monitor/2
    end
  end
end
