package common

const (
	// non-namespaced
	NamespaceKind                = "Namespace"
	StorageClassKind             = "StorageClass"
	ClusterRoleKind              = "ClusterRole"
	ClusterRoleListKind          = "ClusterRoleList"
	ClusterRoleBindingKind       = "ClusterRoleBinding"
	ClusterRoleBindingListKind   = "ClusterRoleBindingList"
	NodeKind                     = "Node"
	CustomResourceDefinitionKind = "CustomResourceDefinition"
	PersistentVolumeKind         = "PersistentVolume"

	// namespaced
	SecretKind                  = "Secret"
	SecretListKind              = "SecretList"
	ServiceKind                 = "Service"
	ServiceAccountKind          = "ServiceAccount"
	EndpointsKind               = "Endpoints"
	DeploymentKind              = "Deployment"
	ReplicaSetKind              = "ReplicaSet"
	StatefulSetKind             = "StatefulSet"
	DaemonSetKind               = "DaemonSet"
	IngressKind                 = "Ingress"
	JobKind                     = "Job"
	PersistentVolumeClaimKind   = "PersistentVolumeClaim"
	PodKind                     = "Pod"
	APIServiceKind              = "APIService"
	HorizontalPodAutoscalerKind = "HorizontalPodAutoscaler"
	CanaryKind                  = "Canary"
	NetworkPolicyKind           = "NetworkPolicy"
	ResourceQuotaKind           = "ResourceQuota"
	LimitRangeKind              = "LimitRange"
	PodDisruptionBudgetKind     = "PodDisruptionBudget"
	PodSecurityPolicyKind       = "PodSecurityPolicy"
	RoleKind                    = "Role"
	RoleListKind                = "RoleList"
	RoleBindingKind             = "RoleBinding"
	RoleBindingListKind         = "RoleBindingList"
	IngressClassKind            = "IngressClass"
	CronJobKind                 = "CronJob"
	ConfigMapKind               = "ConfigMap"
	ReplicationControllerKind   = "ReplicationController"
)
