// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: cmd/kas/kasapp/kasapp.proto

// If you make any changes make sure you run: make regenerate-proto

package kasapp

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/pluralsh/kubernetes-agent/pkg/tool/grpctool/automata"
	prototool "github.com/pluralsh/kubernetes-agent/pkg/tool/prototool"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartStreaming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreaming) Reset() {
	*x = StartStreaming{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreaming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreaming) ProtoMessage() {}

func (x *StartStreaming) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreaming.ProtoReflect.Descriptor instead.
func (*StartStreaming) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{0}
}

type GatewayKasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GatewayKasResponse_TunnelReady_
	//	*GatewayKasResponse_Header_
	//	*GatewayKasResponse_Message_
	//	*GatewayKasResponse_Trailer_
	//	*GatewayKasResponse_Error_
	//	*GatewayKasResponse_NoTunnel_
	Msg           isGatewayKasResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKasResponse) Reset() {
	*x = GatewayKasResponse{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKasResponse) ProtoMessage() {}

func (x *GatewayKasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKasResponse.ProtoReflect.Descriptor instead.
func (*GatewayKasResponse) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayKasResponse) GetMsg() isGatewayKasResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GatewayKasResponse) GetTunnelReady() *GatewayKasResponse_TunnelReady {
	if x != nil {
		if x, ok := x.Msg.(*GatewayKasResponse_TunnelReady_); ok {
			return x.TunnelReady
		}
	}
	return nil
}

func (x *GatewayKasResponse) GetHeader() *GatewayKasResponse_Header {
	if x != nil {
		if x, ok := x.Msg.(*GatewayKasResponse_Header_); ok {
			return x.Header
		}
	}
	return nil
}

func (x *GatewayKasResponse) GetMessage() *GatewayKasResponse_Message {
	if x != nil {
		if x, ok := x.Msg.(*GatewayKasResponse_Message_); ok {
			return x.Message
		}
	}
	return nil
}

func (x *GatewayKasResponse) GetTrailer() *GatewayKasResponse_Trailer {
	if x != nil {
		if x, ok := x.Msg.(*GatewayKasResponse_Trailer_); ok {
			return x.Trailer
		}
	}
	return nil
}

func (x *GatewayKasResponse) GetError() *GatewayKasResponse_Error {
	if x != nil {
		if x, ok := x.Msg.(*GatewayKasResponse_Error_); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GatewayKasResponse) GetNoTunnel() *GatewayKasResponse_NoTunnel {
	if x != nil {
		if x, ok := x.Msg.(*GatewayKasResponse_NoTunnel_); ok {
			return x.NoTunnel
		}
	}
	return nil
}

type isGatewayKasResponse_Msg interface {
	isGatewayKasResponse_Msg()
}

type GatewayKasResponse_TunnelReady_ struct {
	TunnelReady *GatewayKasResponse_TunnelReady `protobuf:"bytes,1,opt,name=tunnel_ready,json=tunnelReady,proto3,oneof"`
}

type GatewayKasResponse_Header_ struct {
	Header *GatewayKasResponse_Header `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type GatewayKasResponse_Message_ struct {
	Message *GatewayKasResponse_Message `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type GatewayKasResponse_Trailer_ struct {
	Trailer *GatewayKasResponse_Trailer `protobuf:"bytes,4,opt,name=trailer,proto3,oneof"`
}

type GatewayKasResponse_Error_ struct {
	Error *GatewayKasResponse_Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type GatewayKasResponse_NoTunnel_ struct {
	NoTunnel *GatewayKasResponse_NoTunnel `protobuf:"bytes,6,opt,name=no_tunnel,json=noTunnel,proto3,oneof"`
}

func (*GatewayKasResponse_TunnelReady_) isGatewayKasResponse_Msg() {}

func (*GatewayKasResponse_Header_) isGatewayKasResponse_Msg() {}

func (*GatewayKasResponse_Message_) isGatewayKasResponse_Msg() {}

func (*GatewayKasResponse_Trailer_) isGatewayKasResponse_Msg() {}

func (*GatewayKasResponse_Error_) isGatewayKasResponse_Msg() {}

func (*GatewayKasResponse_NoTunnel_) isGatewayKasResponse_Msg() {}

// Tunnel is ready, can start forwarding stream.
type GatewayKasResponse_TunnelReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKasResponse_TunnelReady) Reset() {
	*x = GatewayKasResponse_TunnelReady{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKasResponse_TunnelReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKasResponse_TunnelReady) ProtoMessage() {}

func (x *GatewayKasResponse_TunnelReady) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKasResponse_TunnelReady.ProtoReflect.Descriptor instead.
func (*GatewayKasResponse_TunnelReady) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{1, 0}
}

// No tunnels available at the moment.
type GatewayKasResponse_NoTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKasResponse_NoTunnel) Reset() {
	*x = GatewayKasResponse_NoTunnel{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKasResponse_NoTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKasResponse_NoTunnel) ProtoMessage() {}

func (x *GatewayKasResponse_NoTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKasResponse_NoTunnel.ProtoReflect.Descriptor instead.
func (*GatewayKasResponse_NoTunnel) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{1, 1}
}

// Headers is a gRPC metadata.
type GatewayKasResponse_Header struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Meta          map[string]*prototool.Values `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKasResponse_Header) Reset() {
	*x = GatewayKasResponse_Header{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKasResponse_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKasResponse_Header) ProtoMessage() {}

func (x *GatewayKasResponse_Header) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKasResponse_Header.ProtoReflect.Descriptor instead.
func (*GatewayKasResponse_Header) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GatewayKasResponse_Header) GetMeta() map[string]*prototool.Values {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Message is a gRPC message data.
type GatewayKasResponse_Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKasResponse_Message) Reset() {
	*x = GatewayKasResponse_Message{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKasResponse_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKasResponse_Message) ProtoMessage() {}

func (x *GatewayKasResponse_Message) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKasResponse_Message.ProtoReflect.Descriptor instead.
func (*GatewayKasResponse_Message) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{1, 3}
}

func (x *GatewayKasResponse_Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Trailer is a gRPC trailer metadata.
type GatewayKasResponse_Trailer struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Meta          map[string]*prototool.Values `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKasResponse_Trailer) Reset() {
	*x = GatewayKasResponse_Trailer{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKasResponse_Trailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKasResponse_Trailer) ProtoMessage() {}

func (x *GatewayKasResponse_Trailer) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKasResponse_Trailer.ProtoReflect.Descriptor instead.
func (*GatewayKasResponse_Trailer) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{1, 4}
}

func (x *GatewayKasResponse_Trailer) GetMeta() map[string]*prototool.Values {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Error represents a gRPC error that should be returned.
type GatewayKasResponse_Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error status as returned by gRPC.
	// See https://cloud.google.com/apis/design/errors.
	Status        *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKasResponse_Error) Reset() {
	*x = GatewayKasResponse_Error{}
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKasResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKasResponse_Error) ProtoMessage() {}

func (x *GatewayKasResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_kas_kasapp_kasapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKasResponse_Error.ProtoReflect.Descriptor instead.
func (*GatewayKasResponse_Error) Descriptor() ([]byte, []int) {
	return file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP(), []int{1, 5}
}

func (x *GatewayKasResponse_Error) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_cmd_kas_kasapp_kasapp_proto protoreflect.FileDescriptor

const file_cmd_kas_kasapp_kasapp_proto_rawDesc = "" +
	"\n" +
	"\x1bcmd/kas/kasapp/kasapp.proto\x12\x10plural.agent.kas\x1a)pkg/tool/grpctool/automata/automata.proto\x1a\"pkg/tool/prototool/prototool.proto\x1a\x17validate/validate.proto\x1a\x17google/rpc/status.proto\"\x10\n" +
	"\x0eStartStreaming\"\xc6\b\n" +
	"\x12GatewayKasResponse\x12d\n" +
	"\ftunnel_ready\x18\x01 \x01(\v20.plural.agent.kas.GatewayKasResponse.TunnelReadyB\r\xfaB\x05\x8a\x01\x02\x10\x01\x82\xf6,\x01\x02H\x00R\vtunnelReady\x12U\n" +
	"\x06header\x18\x02 \x01(\v2+.plural.agent.kas.GatewayKasResponse.HeaderB\x0e\xfaB\x05\x8a\x01\x02\x10\x01\x82\xf6,\x02\x03\x04H\x00R\x06header\x12X\n" +
	"\amessage\x18\x03 \x01(\v2,.plural.agent.kas.GatewayKasResponse.MessageB\x0e\xfaB\x05\x8a\x01\x02\x10\x01\x82\xf6,\x02\x03\x04H\x00R\amessage\x12a\n" +
	"\atrailer\x18\x04 \x01(\v2,.plural.agent.kas.GatewayKasResponse.TrailerB\x17\xfaB\x05\x8a\x01\x02\x10\x01\x82\xf6,\v\x05\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01H\x00R\atrailer\x12Z\n" +
	"\x05error\x18\x05 \x01(\v2*.plural.agent.kas.GatewayKasResponse.ErrorB\x16\xfaB\x05\x8a\x01\x02\x10\x01\x82\xf6,\n" +
	"\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01H\x00R\x05error\x12e\n" +
	"\tno_tunnel\x18\x06 \x01(\v2-.plural.agent.kas.GatewayKasResponse.NoTunnelB\x17\xfaB\x05\x8a\x01\x02\x10\x01\x82\xf6,\v\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x01H\x00R\bnoTunnel\x1a\r\n" +
	"\vTunnelReady\x1a\n" +
	"\n" +
	"\bNoTunnel\x1a\xac\x01\n" +
	"\x06Header\x12I\n" +
	"\x04meta\x18\x01 \x03(\v25.plural.agent.kas.GatewayKasResponse.Header.MetaEntryR\x04meta\x1aW\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.plural.agent.prototool.ValuesR\x05value:\x028\x01\x1a\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x1a\xae\x01\n" +
	"\aTrailer\x12J\n" +
	"\x04meta\x18\x01 \x03(\v26.plural.agent.kas.GatewayKasResponse.Trailer.MetaEntryR\x04meta\x1aW\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.plural.agent.prototool.ValuesR\x05value:\x028\x01\x1a=\n" +
	"\x05Error\x124\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06statusB\x1a\n" +
	"\x03msg\x12\x13\xf8B\x01\x8a\xf6,\f\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x01\x06B5Z3github.com/pluralsh/kubernetes-agent/cmd/kas/kasappb\x06proto3"

var (
	file_cmd_kas_kasapp_kasapp_proto_rawDescOnce sync.Once
	file_cmd_kas_kasapp_kasapp_proto_rawDescData []byte
)

func file_cmd_kas_kasapp_kasapp_proto_rawDescGZIP() []byte {
	file_cmd_kas_kasapp_kasapp_proto_rawDescOnce.Do(func() {
		file_cmd_kas_kasapp_kasapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_kas_kasapp_kasapp_proto_rawDesc), len(file_cmd_kas_kasapp_kasapp_proto_rawDesc)))
	})
	return file_cmd_kas_kasapp_kasapp_proto_rawDescData
}

var file_cmd_kas_kasapp_kasapp_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cmd_kas_kasapp_kasapp_proto_goTypes = []any{
	(*StartStreaming)(nil),                 // 0: plural.agent.kas.StartStreaming
	(*GatewayKasResponse)(nil),             // 1: plural.agent.kas.GatewayKasResponse
	(*GatewayKasResponse_TunnelReady)(nil), // 2: plural.agent.kas.GatewayKasResponse.TunnelReady
	(*GatewayKasResponse_NoTunnel)(nil),    // 3: plural.agent.kas.GatewayKasResponse.NoTunnel
	(*GatewayKasResponse_Header)(nil),      // 4: plural.agent.kas.GatewayKasResponse.Header
	(*GatewayKasResponse_Message)(nil),     // 5: plural.agent.kas.GatewayKasResponse.Message
	(*GatewayKasResponse_Trailer)(nil),     // 6: plural.agent.kas.GatewayKasResponse.Trailer
	(*GatewayKasResponse_Error)(nil),       // 7: plural.agent.kas.GatewayKasResponse.Error
	nil,                                    // 8: plural.agent.kas.GatewayKasResponse.Header.MetaEntry
	nil,                                    // 9: plural.agent.kas.GatewayKasResponse.Trailer.MetaEntry
	(*status.Status)(nil),                  // 10: google.rpc.Status
	(*prototool.Values)(nil),               // 11: plural.agent.prototool.Values
}
var file_cmd_kas_kasapp_kasapp_proto_depIdxs = []int32{
	2,  // 0: plural.agent.kas.GatewayKasResponse.tunnel_ready:type_name -> plural.agent.kas.GatewayKasResponse.TunnelReady
	4,  // 1: plural.agent.kas.GatewayKasResponse.header:type_name -> plural.agent.kas.GatewayKasResponse.Header
	5,  // 2: plural.agent.kas.GatewayKasResponse.message:type_name -> plural.agent.kas.GatewayKasResponse.Message
	6,  // 3: plural.agent.kas.GatewayKasResponse.trailer:type_name -> plural.agent.kas.GatewayKasResponse.Trailer
	7,  // 4: plural.agent.kas.GatewayKasResponse.error:type_name -> plural.agent.kas.GatewayKasResponse.Error
	3,  // 5: plural.agent.kas.GatewayKasResponse.no_tunnel:type_name -> plural.agent.kas.GatewayKasResponse.NoTunnel
	8,  // 6: plural.agent.kas.GatewayKasResponse.Header.meta:type_name -> plural.agent.kas.GatewayKasResponse.Header.MetaEntry
	9,  // 7: plural.agent.kas.GatewayKasResponse.Trailer.meta:type_name -> plural.agent.kas.GatewayKasResponse.Trailer.MetaEntry
	10, // 8: plural.agent.kas.GatewayKasResponse.Error.status:type_name -> google.rpc.Status
	11, // 9: plural.agent.kas.GatewayKasResponse.Header.MetaEntry.value:type_name -> plural.agent.prototool.Values
	11, // 10: plural.agent.kas.GatewayKasResponse.Trailer.MetaEntry.value:type_name -> plural.agent.prototool.Values
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_cmd_kas_kasapp_kasapp_proto_init() }
func file_cmd_kas_kasapp_kasapp_proto_init() {
	if File_cmd_kas_kasapp_kasapp_proto != nil {
		return
	}
	file_cmd_kas_kasapp_kasapp_proto_msgTypes[1].OneofWrappers = []any{
		(*GatewayKasResponse_TunnelReady_)(nil),
		(*GatewayKasResponse_Header_)(nil),
		(*GatewayKasResponse_Message_)(nil),
		(*GatewayKasResponse_Trailer_)(nil),
		(*GatewayKasResponse_Error_)(nil),
		(*GatewayKasResponse_NoTunnel_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_kas_kasapp_kasapp_proto_rawDesc), len(file_cmd_kas_kasapp_kasapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_kas_kasapp_kasapp_proto_goTypes,
		DependencyIndexes: file_cmd_kas_kasapp_kasapp_proto_depIdxs,
		MessageInfos:      file_cmd_kas_kasapp_kasapp_proto_msgTypes,
	}.Build()
	File_cmd_kas_kasapp_kasapp_proto = out.File
	file_cmd_kas_kasapp_kasapp_proto_goTypes = nil
	file_cmd_kas_kasapp_kasapp_proto_depIdxs = nil
}
