CONTROLLER_CHART_DIR := $(ROOT_DIRECTORY)/charts/controller
PLURAL_CONSOLE_CHART_DIR := $(ROOT_DIRECTORY)/plural/helm/console
WORKSPACES_DIR := $(ROOT_DIRECTORY)/go
TOOLS_DIR := $(WORKSPACES_DIR)/tools
TOOLS_BINARIES_MAKEFILE := $(TOOLS_DIR)/binaries.mk
BOILERPLATE_FILE := $(TOOLS_DIR)/boilerplate.go.txt
CLIENT_DIR := $(WORKSPACES_DIR)/client
CONTROLLER_DIR := $(WORKSPACES_DIR)/controller
