// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: pkg/module/agent_configuration/rpc/rpc.proto

// If you make any changes make sure you run: make regenerate-proto

package rpc

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	agentcfg "github.com/pluralsh/kubernetes-agent/pkg/agentcfg"
	entity "github.com/pluralsh/kubernetes-agent/pkg/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last processed commit id. Optional.
	// Server will only send configuration if the last commit on the branch
	// is a different one. If a connection breaks, this allows to resume
	// the stream without sending the same data again.
	CommitId string `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	// Information about the agent.
	AgentMeta *entity.AgentMeta `protobuf:"bytes,2,opt,name=agent_meta,json=agentMeta,proto3" json:"agent_meta,omitempty"`
	// Flag to skip agent registration.
	SkipRegister  bool `protobuf:"varint,3,opt,name=skip_register,json=skipRegister,proto3" json:"skip_register,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationRequest) Reset() {
	*x = ConfigurationRequest{}
	mi := &file_pkg_module_agent_configuration_rpc_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationRequest) ProtoMessage() {}

func (x *ConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_module_agent_configuration_rpc_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigurationRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *ConfigurationRequest) GetAgentMeta() *entity.AgentMeta {
	if x != nil {
		return x.AgentMeta
	}
	return nil
}

func (x *ConfigurationRequest) GetSkipRegister() bool {
	if x != nil {
		return x.SkipRegister
	}
	return false
}

type ConfigurationResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Configuration *agentcfg.AgentConfiguration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// Commit id of the configuration repository.
	// Can be used to resume connection from where it dropped.
	CommitId      string `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationResponse) Reset() {
	*x = ConfigurationResponse{}
	mi := &file_pkg_module_agent_configuration_rpc_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationResponse) ProtoMessage() {}

func (x *ConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_module_agent_configuration_rpc_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigurationResponse) GetConfiguration() *agentcfg.AgentConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *ConfigurationResponse) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

var File_pkg_module_agent_configuration_rpc_rpc_proto protoreflect.FileDescriptor

const file_pkg_module_agent_configuration_rpc_rpc_proto_rawDesc = "" +
	"\n" +
	",pkg/module/agent_configuration/rpc/rpc.proto\x12$plural.agent.agent_configuration.rpc\x1a\x1bpkg/agentcfg/agentcfg.proto\x1a\x17pkg/entity/entity.proto\x1a\x17validate/validate.proto\"\x97\x01\n" +
	"\x14ConfigurationRequest\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12=\n" +
	"\n" +
	"agent_meta\x18\x02 \x01(\v2\x1e.plural.agent.entity.AgentMetaR\tagentMeta\x12#\n" +
	"\rskip_register\x18\x03 \x01(\bR\fskipRegister\"\x8e\x01\n" +
	"\x15ConfigurationResponse\x12O\n" +
	"\rconfiguration\x18\x01 \x01(\v2).plural.agent.agentcfg.AgentConfigurationR\rconfiguration\x12$\n" +
	"\tcommit_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02 \x01R\bcommitId2\xa6\x01\n" +
	"\x12AgentConfiguration\x12\x8f\x01\n" +
	"\x10GetConfiguration\x12:.plural.agent.agent_configuration.rpc.ConfigurationRequest\x1a;.plural.agent.agent_configuration.rpc.ConfigurationResponse\"\x000\x01BIZGgithub.com/pluralsh/kubernetes-agent/pkg/module/agent_configuration/rpcb\x06proto3"

var (
	file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescOnce sync.Once
	file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescData []byte
)

func file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescGZIP() []byte {
	file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescOnce.Do(func() {
		file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_module_agent_configuration_rpc_rpc_proto_rawDesc), len(file_pkg_module_agent_configuration_rpc_rpc_proto_rawDesc)))
	})
	return file_pkg_module_agent_configuration_rpc_rpc_proto_rawDescData
}

var file_pkg_module_agent_configuration_rpc_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_module_agent_configuration_rpc_rpc_proto_goTypes = []any{
	(*ConfigurationRequest)(nil),        // 0: plural.agent.agent_configuration.rpc.ConfigurationRequest
	(*ConfigurationResponse)(nil),       // 1: plural.agent.agent_configuration.rpc.ConfigurationResponse
	(*entity.AgentMeta)(nil),            // 2: plural.agent.entity.AgentMeta
	(*agentcfg.AgentConfiguration)(nil), // 3: plural.agent.agentcfg.AgentConfiguration
}
var file_pkg_module_agent_configuration_rpc_rpc_proto_depIdxs = []int32{
	2, // 0: plural.agent.agent_configuration.rpc.ConfigurationRequest.agent_meta:type_name -> plural.agent.entity.AgentMeta
	3, // 1: plural.agent.agent_configuration.rpc.ConfigurationResponse.configuration:type_name -> plural.agent.agentcfg.AgentConfiguration
	0, // 2: plural.agent.agent_configuration.rpc.AgentConfiguration.GetConfiguration:input_type -> plural.agent.agent_configuration.rpc.ConfigurationRequest
	1, // 3: plural.agent.agent_configuration.rpc.AgentConfiguration.GetConfiguration:output_type -> plural.agent.agent_configuration.rpc.ConfigurationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_module_agent_configuration_rpc_rpc_proto_init() }
func file_pkg_module_agent_configuration_rpc_rpc_proto_init() {
	if File_pkg_module_agent_configuration_rpc_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_module_agent_configuration_rpc_rpc_proto_rawDesc), len(file_pkg_module_agent_configuration_rpc_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_module_agent_configuration_rpc_rpc_proto_goTypes,
		DependencyIndexes: file_pkg_module_agent_configuration_rpc_rpc_proto_depIdxs,
		MessageInfos:      file_pkg_module_agent_configuration_rpc_rpc_proto_msgTypes,
	}.Build()
	File_pkg_module_agent_configuration_rpc_rpc_proto = out.File
	file_pkg_module_agent_configuration_rpc_rpc_proto_goTypes = nil
	file_pkg_module_agent_configuration_rpc_rpc_proto_depIdxs = nil
}
