{{- if .Values.aiProxy.enabled -}}
{{- $config := deepCopy .Values.aiProxy.config -}}
{{- if .Values.aiProxy.tls.enabled -}}
{{- $_ := set $config.server "certificateFile" "/etc/nexus/tls/tls.crt" -}}
{{- $_ := set $config.server "keyFile" "/etc/nexus/tls/tls.key" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-config
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{ toYaml $config | indent 4 }}
{{- end }}
