ARG VERSION=1.24

ARG AGENT_HARNESS_IMAGE_TAG
ARG AGENT_HARNESS_IMAGE_REPO
ARG AGENT_HARNESS_IMAGE=$AGENT_HARNESS_IMAGE_REPO:$AGENT_HARNESS_IMAGE_TAG

FROM golang:${VERSION} AS golang

FROM $AGENT_HARNESS_IMAGE AS final

COPY --from=golang /usr/local /usr/local
COPY --from=golang /go /go

ENV GOPATH=/go
ENV PATH=/usr/local/go/bin:${GOPATH}/bin:${PATH}

USER 65532:65532
