ARG VERSION=3.14

ARG AGENT_HARNESS_IMAGE_TAG
ARG AGENT_HARNESS_IMAGE_REPO
ARG AGENT_HARNESS_IMAGE=$AGENT_HARNESS_IMAGE_REPO:$AGENT_HARNESS_IMAGE_TAG

FROM python:${VERSION}-slim AS python

FROM $AGENT_HARNESS_IMAGE AS final

COPY --from=python /usr/local /usr/local
COPY --from=python /usr/lib /usr/lib

USER 65532:65532
