// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: console.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AiConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiConfigRequest) Reset() {
	*x = AiConfigRequest{}
	mi := &file_console_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiConfigRequest) ProtoMessage() {}

func (x *AiConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiConfigRequest.ProtoReflect.Descriptor instead.
func (*AiConfigRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{0}
}

type AiConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Openai        *OpenAiConfig          `protobuf:"bytes,2,opt,name=openai,proto3" json:"openai,omitempty"`
	Anthropic     *AnthropicConfig       `protobuf:"bytes,3,opt,name=anthropic,proto3" json:"anthropic,omitempty"`
	VertexAi      *VertexAiConfig        `protobuf:"bytes,4,opt,name=vertexAi,proto3" json:"vertexAi,omitempty"`
	Bedrock       *BedrockConfig         `protobuf:"bytes,5,opt,name=bedrock,proto3" json:"bedrock,omitempty"`
	Azure         *AzureOpenAiConfig     `protobuf:"bytes,6,opt,name=azure,proto3" json:"azure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiConfig) Reset() {
	*x = AiConfig{}
	mi := &file_console_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiConfig) ProtoMessage() {}

func (x *AiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiConfig.ProtoReflect.Descriptor instead.
func (*AiConfig) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{1}
}

func (x *AiConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AiConfig) GetOpenai() *OpenAiConfig {
	if x != nil {
		return x.Openai
	}
	return nil
}

func (x *AiConfig) GetAnthropic() *AnthropicConfig {
	if x != nil {
		return x.Anthropic
	}
	return nil
}

func (x *AiConfig) GetVertexAi() *VertexAiConfig {
	if x != nil {
		return x.VertexAi
	}
	return nil
}

func (x *AiConfig) GetBedrock() *BedrockConfig {
	if x != nil {
		return x.Bedrock
	}
	return nil
}

func (x *AiConfig) GetAzure() *AzureOpenAiConfig {
	if x != nil {
		return x.Azure
	}
	return nil
}

type OpenAiConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiKey         *string                `protobuf:"bytes,1,opt,name=apiKey,proto3,oneof" json:"apiKey,omitempty"`
	Model          *string                `protobuf:"bytes,2,opt,name=model,proto3,oneof" json:"model,omitempty"`
	EmbeddingModel *string                `protobuf:"bytes,3,opt,name=embeddingModel,proto3,oneof" json:"embeddingModel,omitempty"`
	ToolModel      *string                `protobuf:"bytes,4,opt,name=toolModel,proto3,oneof" json:"toolModel,omitempty"`
	BaseUrl        *string                `protobuf:"bytes,5,opt,name=baseUrl,proto3,oneof" json:"baseUrl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpenAiConfig) Reset() {
	*x = OpenAiConfig{}
	mi := &file_console_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAiConfig) ProtoMessage() {}

func (x *OpenAiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAiConfig.ProtoReflect.Descriptor instead.
func (*OpenAiConfig) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAiConfig) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *OpenAiConfig) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *OpenAiConfig) GetEmbeddingModel() string {
	if x != nil && x.EmbeddingModel != nil {
		return *x.EmbeddingModel
	}
	return ""
}

func (x *OpenAiConfig) GetToolModel() string {
	if x != nil && x.ToolModel != nil {
		return *x.ToolModel
	}
	return ""
}

func (x *OpenAiConfig) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

type AnthropicConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl        *string                `protobuf:"bytes,1,opt,name=baseUrl,proto3,oneof" json:"baseUrl,omitempty"`
	ApiKey         *string                `protobuf:"bytes,2,opt,name=apiKey,proto3,oneof" json:"apiKey,omitempty"`
	Model          *string                `protobuf:"bytes,3,opt,name=model,proto3,oneof" json:"model,omitempty"`
	EmbeddingModel *string                `protobuf:"bytes,4,opt,name=embeddingModel,proto3,oneof" json:"embeddingModel,omitempty"`
	ToolModel      *string                `protobuf:"bytes,5,opt,name=toolModel,proto3,oneof" json:"toolModel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnthropicConfig) Reset() {
	*x = AnthropicConfig{}
	mi := &file_console_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicConfig) ProtoMessage() {}

func (x *AnthropicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicConfig.ProtoReflect.Descriptor instead.
func (*AnthropicConfig) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{3}
}

func (x *AnthropicConfig) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *AnthropicConfig) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *AnthropicConfig) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *AnthropicConfig) GetEmbeddingModel() string {
	if x != nil && x.EmbeddingModel != nil {
		return *x.EmbeddingModel
	}
	return ""
}

func (x *AnthropicConfig) GetToolModel() string {
	if x != nil && x.ToolModel != nil {
		return *x.ToolModel
	}
	return ""
}

type VertexAiConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApiKey             *string                `protobuf:"bytes,1,opt,name=apiKey,proto3,oneof" json:"apiKey,omitempty"`
	Model              *string                `protobuf:"bytes,2,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Endpoint           *string                `protobuf:"bytes,3,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	ServiceAccountJson *string                `protobuf:"bytes,4,opt,name=serviceAccountJson,proto3,oneof" json:"serviceAccountJson,omitempty"`
	EmbeddingModel     *string                `protobuf:"bytes,5,opt,name=embeddingModel,proto3,oneof" json:"embeddingModel,omitempty"`
	ToolModel          *string                `protobuf:"bytes,6,opt,name=toolModel,proto3,oneof" json:"toolModel,omitempty"`
	Project            *string                `protobuf:"bytes,7,opt,name=project,proto3,oneof" json:"project,omitempty"`
	Location           *string                `protobuf:"bytes,8,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VertexAiConfig) Reset() {
	*x = VertexAiConfig{}
	mi := &file_console_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VertexAiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertexAiConfig) ProtoMessage() {}

func (x *VertexAiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertexAiConfig.ProtoReflect.Descriptor instead.
func (*VertexAiConfig) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{4}
}

func (x *VertexAiConfig) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *VertexAiConfig) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *VertexAiConfig) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *VertexAiConfig) GetServiceAccountJson() string {
	if x != nil && x.ServiceAccountJson != nil {
		return *x.ServiceAccountJson
	}
	return ""
}

func (x *VertexAiConfig) GetEmbeddingModel() string {
	if x != nil && x.EmbeddingModel != nil {
		return *x.EmbeddingModel
	}
	return ""
}

func (x *VertexAiConfig) GetToolModel() string {
	if x != nil && x.ToolModel != nil {
		return *x.ToolModel
	}
	return ""
}

func (x *VertexAiConfig) GetProject() string {
	if x != nil && x.Project != nil {
		return *x.Project
	}
	return ""
}

func (x *VertexAiConfig) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

type BedrockConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ModelId            *string                `protobuf:"bytes,1,opt,name=modelId,proto3,oneof" json:"modelId,omitempty"`
	ToolModelId        *string                `protobuf:"bytes,2,opt,name=toolModelId,proto3,oneof" json:"toolModelId,omitempty"`
	AccessToken        *string                `protobuf:"bytes,3,opt,name=accessToken,proto3,oneof" json:"accessToken,omitempty"`
	Region             *string                `protobuf:"bytes,4,opt,name=region,proto3,oneof" json:"region,omitempty"`
	EmbeddingModelId   *string                `protobuf:"bytes,5,opt,name=embeddingModelId,proto3,oneof" json:"embeddingModelId,omitempty"`
	AwsAccessKeyId     *string                `protobuf:"bytes,6,opt,name=awsAccessKeyId,proto3,oneof" json:"awsAccessKeyId,omitempty"`
	AwsSecretAccessKey *string                `protobuf:"bytes,7,opt,name=awsSecretAccessKey,proto3,oneof" json:"awsSecretAccessKey,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BedrockConfig) Reset() {
	*x = BedrockConfig{}
	mi := &file_console_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedrockConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedrockConfig) ProtoMessage() {}

func (x *BedrockConfig) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedrockConfig.ProtoReflect.Descriptor instead.
func (*BedrockConfig) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{5}
}

func (x *BedrockConfig) GetModelId() string {
	if x != nil && x.ModelId != nil {
		return *x.ModelId
	}
	return ""
}

func (x *BedrockConfig) GetToolModelId() string {
	if x != nil && x.ToolModelId != nil {
		return *x.ToolModelId
	}
	return ""
}

func (x *BedrockConfig) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *BedrockConfig) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *BedrockConfig) GetEmbeddingModelId() string {
	if x != nil && x.EmbeddingModelId != nil {
		return *x.EmbeddingModelId
	}
	return ""
}

func (x *BedrockConfig) GetAwsAccessKeyId() string {
	if x != nil && x.AwsAccessKeyId != nil {
		return *x.AwsAccessKeyId
	}
	return ""
}

func (x *BedrockConfig) GetAwsSecretAccessKey() string {
	if x != nil && x.AwsSecretAccessKey != nil {
		return *x.AwsSecretAccessKey
	}
	return ""
}

type AzureOpenAiConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion     *string                `protobuf:"bytes,1,opt,name=apiVersion,proto3,oneof" json:"apiVersion,omitempty"`
	Model          *string                `protobuf:"bytes,2,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Endpoint       *string                `protobuf:"bytes,4,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	EmbeddingModel *string                `protobuf:"bytes,5,opt,name=embeddingModel,proto3,oneof" json:"embeddingModel,omitempty"`
	ToolModel      *string                `protobuf:"bytes,6,opt,name=toolModel,proto3,oneof" json:"toolModel,omitempty"`
	AccessToken    *string                `protobuf:"bytes,7,opt,name=accessToken,proto3,oneof" json:"accessToken,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AzureOpenAiConfig) Reset() {
	*x = AzureOpenAiConfig{}
	mi := &file_console_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureOpenAiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureOpenAiConfig) ProtoMessage() {}

func (x *AzureOpenAiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureOpenAiConfig.ProtoReflect.Descriptor instead.
func (*AzureOpenAiConfig) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{6}
}

func (x *AzureOpenAiConfig) GetApiVersion() string {
	if x != nil && x.ApiVersion != nil {
		return *x.ApiVersion
	}
	return ""
}

func (x *AzureOpenAiConfig) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *AzureOpenAiConfig) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *AzureOpenAiConfig) GetEmbeddingModel() string {
	if x != nil && x.EmbeddingModel != nil {
		return *x.EmbeddingModel
	}
	return ""
}

func (x *AzureOpenAiConfig) GetToolModel() string {
	if x != nil && x.ToolModel != nil {
		return *x.ToolModel
	}
	return ""
}

func (x *AzureOpenAiConfig) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

type ProxyAuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyAuthenticationRequest) Reset() {
	*x = ProxyAuthenticationRequest{}
	mi := &file_console_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyAuthenticationRequest) ProtoMessage() {}

func (x *ProxyAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*ProxyAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{7}
}

func (x *ProxyAuthenticationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ProxyAuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyAuthenticationResponse) Reset() {
	*x = ProxyAuthenticationResponse{}
	mi := &file_console_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyAuthenticationResponse) ProtoMessage() {}

func (x *ProxyAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*ProxyAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{8}
}

func (x *ProxyAuthenticationResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

var File_console_proto protoreflect.FileDescriptor

const file_console_proto_rawDesc = "" +
	"\n" +
	"\rconsole.proto\x12\x04plrl\"\x11\n" +
	"\x0fAiConfigRequest\"\x95\x02\n" +
	"\bAiConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12*\n" +
	"\x06openai\x18\x02 \x01(\v2\x12.plrl.OpenAiConfigR\x06openai\x123\n" +
	"\tanthropic\x18\x03 \x01(\v2\x15.plrl.AnthropicConfigR\tanthropic\x120\n" +
	"\bvertexAi\x18\x04 \x01(\v2\x14.plrl.VertexAiConfigR\bvertexAi\x12-\n" +
	"\abedrock\x18\x05 \x01(\v2\x13.plrl.BedrockConfigR\abedrock\x12-\n" +
	"\x05azure\x18\x06 \x01(\v2\x17.plrl.AzureOpenAiConfigR\x05azure\"\xf7\x01\n" +
	"\fOpenAiConfig\x12\x1b\n" +
	"\x06apiKey\x18\x01 \x01(\tH\x00R\x06apiKey\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x02 \x01(\tH\x01R\x05model\x88\x01\x01\x12+\n" +
	"\x0eembeddingModel\x18\x03 \x01(\tH\x02R\x0eembeddingModel\x88\x01\x01\x12!\n" +
	"\ttoolModel\x18\x04 \x01(\tH\x03R\ttoolModel\x88\x01\x01\x12\x1d\n" +
	"\abaseUrl\x18\x05 \x01(\tH\x04R\abaseUrl\x88\x01\x01B\t\n" +
	"\a_apiKeyB\b\n" +
	"\x06_modelB\x11\n" +
	"\x0f_embeddingModelB\f\n" +
	"\n" +
	"_toolModelB\n" +
	"\n" +
	"\b_baseUrl\"\xfa\x01\n" +
	"\x0fAnthropicConfig\x12\x1d\n" +
	"\abaseUrl\x18\x01 \x01(\tH\x00R\abaseUrl\x88\x01\x01\x12\x1b\n" +
	"\x06apiKey\x18\x02 \x01(\tH\x01R\x06apiKey\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x03 \x01(\tH\x02R\x05model\x88\x01\x01\x12+\n" +
	"\x0eembeddingModel\x18\x04 \x01(\tH\x03R\x0eembeddingModel\x88\x01\x01\x12!\n" +
	"\ttoolModel\x18\x05 \x01(\tH\x04R\ttoolModel\x88\x01\x01B\n" +
	"\n" +
	"\b_baseUrlB\t\n" +
	"\a_apiKeyB\b\n" +
	"\x06_modelB\x11\n" +
	"\x0f_embeddingModelB\f\n" +
	"\n" +
	"_toolModel\"\xa1\x03\n" +
	"\x0eVertexAiConfig\x12\x1b\n" +
	"\x06apiKey\x18\x01 \x01(\tH\x00R\x06apiKey\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x02 \x01(\tH\x01R\x05model\x88\x01\x01\x12\x1f\n" +
	"\bendpoint\x18\x03 \x01(\tH\x02R\bendpoint\x88\x01\x01\x123\n" +
	"\x12serviceAccountJson\x18\x04 \x01(\tH\x03R\x12serviceAccountJson\x88\x01\x01\x12+\n" +
	"\x0eembeddingModel\x18\x05 \x01(\tH\x04R\x0eembeddingModel\x88\x01\x01\x12!\n" +
	"\ttoolModel\x18\x06 \x01(\tH\x05R\ttoolModel\x88\x01\x01\x12\x1d\n" +
	"\aproject\x18\a \x01(\tH\x06R\aproject\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\b \x01(\tH\aR\blocation\x88\x01\x01B\t\n" +
	"\a_apiKeyB\b\n" +
	"\x06_modelB\v\n" +
	"\t_endpointB\x15\n" +
	"\x13_serviceAccountJsonB\x11\n" +
	"\x0f_embeddingModelB\f\n" +
	"\n" +
	"_toolModelB\n" +
	"\n" +
	"\b_projectB\v\n" +
	"\t_location\"\xa2\x03\n" +
	"\rBedrockConfig\x12\x1d\n" +
	"\amodelId\x18\x01 \x01(\tH\x00R\amodelId\x88\x01\x01\x12%\n" +
	"\vtoolModelId\x18\x02 \x01(\tH\x01R\vtoolModelId\x88\x01\x01\x12%\n" +
	"\vaccessToken\x18\x03 \x01(\tH\x02R\vaccessToken\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x04 \x01(\tH\x03R\x06region\x88\x01\x01\x12/\n" +
	"\x10embeddingModelId\x18\x05 \x01(\tH\x04R\x10embeddingModelId\x88\x01\x01\x12+\n" +
	"\x0eawsAccessKeyId\x18\x06 \x01(\tH\x05R\x0eawsAccessKeyId\x88\x01\x01\x123\n" +
	"\x12awsSecretAccessKey\x18\a \x01(\tH\x06R\x12awsSecretAccessKey\x88\x01\x01B\n" +
	"\n" +
	"\b_modelIdB\x0e\n" +
	"\f_toolModelIdB\x0e\n" +
	"\f_accessTokenB\t\n" +
	"\a_regionB\x13\n" +
	"\x11_embeddingModelIdB\x11\n" +
	"\x0f_awsAccessKeyIdB\x15\n" +
	"\x13_awsSecretAccessKey\"\xc2\x02\n" +
	"\x11AzureOpenAiConfig\x12#\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tH\x00R\n" +
	"apiVersion\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x02 \x01(\tH\x01R\x05model\x88\x01\x01\x12\x1f\n" +
	"\bendpoint\x18\x04 \x01(\tH\x02R\bendpoint\x88\x01\x01\x12+\n" +
	"\x0eembeddingModel\x18\x05 \x01(\tH\x03R\x0eembeddingModel\x88\x01\x01\x12!\n" +
	"\ttoolModel\x18\x06 \x01(\tH\x04R\ttoolModel\x88\x01\x01\x12%\n" +
	"\vaccessToken\x18\a \x01(\tH\x05R\vaccessToken\x88\x01\x01B\r\n" +
	"\v_apiVersionB\b\n" +
	"\x06_modelB\v\n" +
	"\t_endpointB\x11\n" +
	"\x0f_embeddingModelB\f\n" +
	"\n" +
	"_toolModelB\x0e\n" +
	"\f_accessToken\"2\n" +
	"\x1aProxyAuthenticationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"C\n" +
	"\x1bProxyAuthenticationResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated2\xa0\x01\n" +
	"\fPluralServer\x124\n" +
	"\vGetAiConfig\x12\x15.plrl.AiConfigRequest\x1a\x0e.plrl.AiConfig\x12Z\n" +
	"\x13ProxyAuthentication\x12 .plrl.ProxyAuthenticationRequest\x1a!.plrl.ProxyAuthenticationResponseB\x10Z\x0einternal/protob\x06proto3"

var (
	file_console_proto_rawDescOnce sync.Once
	file_console_proto_rawDescData []byte
)

func file_console_proto_rawDescGZIP() []byte {
	file_console_proto_rawDescOnce.Do(func() {
		file_console_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_proto_rawDesc), len(file_console_proto_rawDesc)))
	})
	return file_console_proto_rawDescData
}

var file_console_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_console_proto_goTypes = []any{
	(*AiConfigRequest)(nil),             // 0: plrl.AiConfigRequest
	(*AiConfig)(nil),                    // 1: plrl.AiConfig
	(*OpenAiConfig)(nil),                // 2: plrl.OpenAiConfig
	(*AnthropicConfig)(nil),             // 3: plrl.AnthropicConfig
	(*VertexAiConfig)(nil),              // 4: plrl.VertexAiConfig
	(*BedrockConfig)(nil),               // 5: plrl.BedrockConfig
	(*AzureOpenAiConfig)(nil),           // 6: plrl.AzureOpenAiConfig
	(*ProxyAuthenticationRequest)(nil),  // 7: plrl.ProxyAuthenticationRequest
	(*ProxyAuthenticationResponse)(nil), // 8: plrl.ProxyAuthenticationResponse
}
var file_console_proto_depIdxs = []int32{
	2, // 0: plrl.AiConfig.openai:type_name -> plrl.OpenAiConfig
	3, // 1: plrl.AiConfig.anthropic:type_name -> plrl.AnthropicConfig
	4, // 2: plrl.AiConfig.vertexAi:type_name -> plrl.VertexAiConfig
	5, // 3: plrl.AiConfig.bedrock:type_name -> plrl.BedrockConfig
	6, // 4: plrl.AiConfig.azure:type_name -> plrl.AzureOpenAiConfig
	0, // 5: plrl.PluralServer.GetAiConfig:input_type -> plrl.AiConfigRequest
	7, // 6: plrl.PluralServer.ProxyAuthentication:input_type -> plrl.ProxyAuthenticationRequest
	1, // 7: plrl.PluralServer.GetAiConfig:output_type -> plrl.AiConfig
	8, // 8: plrl.PluralServer.ProxyAuthentication:output_type -> plrl.ProxyAuthenticationResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_console_proto_init() }
func file_console_proto_init() {
	if File_console_proto != nil {
		return
	}
	file_console_proto_msgTypes[2].OneofWrappers = []any{}
	file_console_proto_msgTypes[3].OneofWrappers = []any{}
	file_console_proto_msgTypes[4].OneofWrappers = []any{}
	file_console_proto_msgTypes[5].OneofWrappers = []any{}
	file_console_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_proto_rawDesc), len(file_console_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_proto_goTypes,
		DependencyIndexes: file_console_proto_depIdxs,
		MessageInfos:      file_console_proto_msgTypes,
	}.Build()
	File_console_proto = out.File
	file_console_proto_goTypes = nil
	file_console_proto_depIdxs = nil
}
