/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"fmt"
	"strconv"

	"github.com/samber/lo"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	console "github.com/pluralsh/console/go/client"
)

func init() {
	SchemeBuilder.Register(&Monitor{}, &MonitorList{})
}

// +kubebuilder:object:root=true

// MonitorList contains a list of Monitor resources.
type MonitorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Monitor `json:"items"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ID",type="string",JSONPath=".status.id",description="ID of the Monitor in the Console API."
// +kubebuilder:printcolumn:name="TYPE",type="string",JSONPath=".spec.type",description="Monitor data type."
// +kubebuilder:printcolumn:name="SEVERITY",type="string",JSONPath=".spec.severity",description="Severity of alerts generated by this Monitor."
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].status",description="Whether the Monitor is ready."

// Monitor represents an observability monitor attached to a service deployment. It periodically
// evaluates a log or metrics query against a threshold and fires alerts when it is crossed.
// Optionally, it can be attached to a workbench to start an investigation when it fires.
type Monitor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec defines the desired state of the Monitor.
	// +kubebuilder:validation:Required
	Spec MonitorSpec `json:"spec"`

	// Status represents the current state of this resource.
	// +kubebuilder:validation:Optional
	Status Status `json:"status,omitempty"`
}

// SetReadOnlyStatus sets the read-only status of the monitor.
func (in *Monitor) SetReadOnlyStatus(readOnly bool) {
	in.Status.ReadOnly = readOnly
}

// ConsoleID implements [PluralResource] interface.
func (in *Monitor) ConsoleID() *string {
	return in.Status.ID
}

// ConsoleName implements [PluralResource] interface.
func (in *Monitor) ConsoleName() string {
	if in.Spec.Name != nil && len(*in.Spec.Name) > 0 {
		return *in.Spec.Name
	}
	return in.Name
}

// Diff compares the current Monitor spec with its last known state.
func (in *Monitor) Diff(hasher Hasher) (changed bool, sha string, err error) {
	currentSha, err := hasher(in.Spec)
	if err != nil {
		return false, "", err
	}
	return !in.Status.IsSHAEqual(currentSha), currentSha, nil
}

// SetCondition sets a condition on the Monitor status.
func (in *Monitor) SetCondition(condition metav1.Condition) {
	meta.SetStatusCondition(&in.Status.Conditions, condition)
}

// Attributes converts the Monitor spec into Console API attributes.
// The serviceID (from ServiceRef or Service) and workbenchID have to be resolved from the spec by the caller.
func (in *Monitor) Attributes(serviceID string, workbenchID *string) (*console.MonitorAttributes, error) {
	threshold, err := in.Spec.Threshold.Attributes()
	if err != nil {
		return nil, err
	}

	modes, err := in.Spec.Modes.Attributes()
	if err != nil {
		return nil, err
	}

	return &console.MonitorAttributes{
		ServiceID:      serviceID,
		WorkbenchID:    workbenchID,
		Prompt:         in.Spec.Prompt,
		Modes:          modes,
		Name:           in.ConsoleName(),
		Description:    in.Spec.Description,
		AlertTemplate:  in.Spec.AlertTemplate,
		Severity:       in.Spec.Severity,
		Type:           in.Spec.Type,
		EvaluationCron: in.Spec.EvaluationCron,
		Query:          in.Spec.Query.Attributes(),
		Threshold:      *threshold,
	}, nil
}

// MonitorSpec defines the desired state of a Monitor.
// +kubebuilder:validation:XValidation:rule="has(self.serviceRef) != has(self.service)",message="exactly one of serviceRef or service must be set"
// +kubebuilder:validation:XValidation:rule="self.type != 'LOG' || has(self.query.log)",message="query.log must be set when type is LOG"
// +kubebuilder:validation:XValidation:rule="self.type != 'METRICS' || has(self.query.metrics)",message="query.metrics must be set when type is METRICS"
// +kubebuilder:validation:XValidation:rule="has(self.workbenchRef) || !((has(self.query.log) && has(self.query.log.tool)) || (has(self.query.metrics) && has(self.query.metrics.tool)))",message="workbenchRef is required for tool-backed monitor queries"
type MonitorSpec struct {
	// Name is the short name used to identify this monitor in the Console API.
	// If not set, metadata.name is used.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	Name *string `json:"name,omitempty"`

	// ServiceRef references the ServiceDeployment resource this monitor is attached to.
	// The ServiceDeployment must be in the same namespace as the monitor.
	// Either ServiceRef or Service must be set.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:XValidation:rule="has(self.name) && size(self.name) > 0",message="name is required"
	ServiceRef *corev1.LocalObjectReference `json:"serviceRef,omitempty"`

	// Service references an existing service in the Console API this monitor is attached to,
	// in the format "cluster-handle/service-name" (e.g. mgmt/console). Use it to attach
	// a monitor to a service that is not managed by a ServiceDeployment resource.
	// Either ServiceRef or Service must be set.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:Pattern=`^[^/]+/[^/]+$`
	// +kubebuilder:example:=mgmt/console
	Service *string `json:"service,omitempty"`

	// WorkbenchRef references the Workbench this monitor is attached to.
	// When set, the monitor can start a workbench investigation when it fires.
	// It is required if the query uses a named workbench tool.
	// The Workbench must be in the same namespace as the monitor.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:XValidation:rule="has(self.name) && size(self.name) > 0",message="name is required"
	WorkbenchRef *corev1.LocalObjectReference `json:"workbenchRef,omitempty"`

	// Prompt is used when the monitor starts a workbench investigation.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:MaxLength=2048
	Prompt *string `json:"prompt,omitempty"`

	// Modes defines mode-specific options for monitor-triggered workbench jobs.
	// +kubebuilder:validation:Optional
	Modes *WorkbenchJobModes `json:"modes,omitempty"`

	// Description is an optional free-form description of what this monitor is checking.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	Description *string `json:"description,omitempty"`

	// AlertTemplate is an optional template used when rendering alert messages for this monitor.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	AlertTemplate *string `json:"alertTemplate,omitempty"`

	// Severity is the severity level applied to alerts generated by this monitor.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=LOW;MEDIUM;HIGH;CRITICAL;UNDEFINED
	Severity console.AlertSeverity `json:"severity"`

	// Type is the monitor data type.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=LOG;METRICS
	Type console.MonitorType `json:"type"`

	// EvaluationCron is the cron schedule defining when the monitor is evaluated (e.g. */5 * * * *).
	// It must be a cron expression with 5 fields (or 6 with an optional year), separated by single spaces,
	// or one of the @yearly, @annually, @monthly, @weekly, @daily, @midnight, @hourly, @minutely,
	// @secondly or @reboot shortcuts. Field values are validated by the Console API.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Pattern=`^(@(?i:yearly|annually|monthly|weekly|daily|midnight|hourly|minutely|secondly|reboot)|[^ ]+( [^ ]+){4,5})$`
	EvaluationCron string `json:"evaluationCron"`

	// Query is the underlying query configuration used to fetch data for this monitor.
	// +kubebuilder:validation:Required
	Query MonitorQuery `json:"query"`

	// Threshold is the configuration that determines when the monitor should fire.
	// +kubebuilder:validation:Required
	Threshold MonitorThreshold `json:"threshold"`

	// Reconciliation settings for this resource.
	// +kubebuilder:validation:Optional
	Reconciliation *Reconciliation `json:"reconciliation,omitempty"`
}

// MonitorThreshold is the threshold configuration used to decide when a monitor should fire.
type MonitorThreshold struct {
	// Aggregate is the aggregation function applied over the result set.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=MAX;MIN;AVG
	Aggregate console.MonitorAggregate `json:"aggregate"`

	// Value is the numeric value the aggregated metric must cross to trigger the alert.
	// It is a string to allow decimal values (e.g. "0.95").
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:Pattern=`^-?[0-9]+(\.[0-9]+)?$`
	Value string `json:"value"`
}

func (in *MonitorThreshold) Attributes() (*console.MonitorThresholdAttributes, error) {
	value, err := strconv.ParseFloat(in.Value, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid threshold value %q: %w", in.Value, err)
	}

	return &console.MonitorThresholdAttributes{
		Aggregate: in.Aggregate,
		Value:     value,
	}, nil
}

// MonitorQuery is a wrapper for the underlying query definition for a monitor.
// Exactly one of log or metrics should be set, matching the monitor type.
// +kubebuilder:validation:XValidation:rule="!(has(self.log) && has(self.metrics))",message="only one of log or metrics can be set"
type MonitorQuery struct {
	// Log query used when the monitor type is LOG.
	// +kubebuilder:validation:Optional
	Log *MonitorLogQuery `json:"log,omitempty"`

	// Metrics query used when the monitor type is METRICS.
	// +kubebuilder:validation:Optional
	Metrics *MonitorMetricsQuery `json:"metrics,omitempty"`
}

func (in *MonitorQuery) Attributes() console.MonitorQueryAttributes {
	return console.MonitorQueryAttributes{
		Log:     in.Log.Attributes(),
		Metrics: in.Metrics.Attributes(),
	}
}

// MonitorLogQuery is the log query configuration for a monitor.
type MonitorLogQuery struct {
	// Tool is the named workbench logs tool. When omitted, the native Plural logs provider is used.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	Tool *string `json:"tool,omitempty"`

	// Query is the log query string passed through to the underlying log provider.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:MinLength=1
	Query string `json:"query"`

	// BucketSize is the time bucket size (e.g. 5m) used when aggregating log results.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:Pattern=`^[0-9]+[dmhs]$`
	BucketSize string `json:"bucketSize"`

	// Duration is the lookback duration for the log query (e.g. 1h, 10m, 30s).
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:Pattern=`^[0-9]+[dmhs]$`
	Duration *string `json:"duration,omitempty"`

	// Operator to use when combining multiple log queries.
	// Defaults to OR, which is also the Console API default.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=OR;AND
	// +kubebuilder:default=OR
	Operator *console.MonitorOperator `json:"operator,omitempty"`

	// Facets are optional key/value facets applied as additional filters on the log query.
	// +kubebuilder:validation:Optional
	Facets []MonitorFacet `json:"facets,omitempty"`

	// Options are provider-specific log query options.
	// +kubebuilder:validation:Optional
	Options *MonitorLogOptions `json:"options,omitempty"`
}

func (in *MonitorLogQuery) Attributes() *console.MonitorLogQueryAttributes {
	if in == nil {
		return nil
	}

	return &console.MonitorLogQueryAttributes{
		Tool:       in.Tool,
		Query:      in.Query,
		BucketSize: in.BucketSize,
		Duration:   in.Duration,
		Operator:   in.Operator,
		Facets: lo.Map(in.Facets, func(f MonitorFacet, _ int) *console.MonitorFacetAttributes {
			return &console.MonitorFacetAttributes{Key: f.Key, Value: f.Value}
		}),
		Options: in.Options.Attributes(),
	}
}

// MonitorFacet is a key/value facet used to further filter log queries.
type MonitorFacet struct {
	// Key is the facet key (e.g. kubernetes namespace or pod label name).
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Type:=string
	Key string `json:"key"`

	// Value is the facet value to match for the given key.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Type:=string
	Value string `json:"value"`
}

// MonitorLogOptions are provider-specific log query options.
type MonitorLogOptions struct {
	// Azure log query options.
	// +kubebuilder:validation:Optional
	Azure *MonitorLogAzureOptions `json:"azure,omitempty"`
}

func (in *MonitorLogOptions) Attributes() *console.MonitorLogOptionsAttributes {
	if in == nil {
		return nil
	}

	var azure *console.MonitorLogAzureOptionsAttributes
	if in.Azure != nil {
		azure = &console.MonitorLogAzureOptionsAttributes{ResourceID: in.Azure.ResourceID}
	}

	return &console.MonitorLogOptionsAttributes{Azure: azure}
}

// MonitorLogAzureOptions are Azure-specific log query options.
type MonitorLogAzureOptions struct {
	// ResourceID is the Azure resource ID to query logs for.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	ResourceID *string `json:"resourceId,omitempty"`
}

// MonitorMetricsQuery is the metrics query configuration for a monitor.
type MonitorMetricsQuery struct {
	// Tool is the named workbench metrics tool. When omitted, the native Plural metrics provider is used.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	Tool *string `json:"tool,omitempty"`

	// Query is the metrics query string passed through to the underlying metrics provider.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:MinLength=1
	Query string `json:"query"`

	// Step is the metrics query step (e.g. 5m).
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:Pattern=`^[0-9]+[dmhs]$`
	Step *string `json:"step,omitempty"`

	// Duration is the lookback duration for the metrics query (e.g. 1h).
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	// +kubebuilder:validation:Pattern=`^[0-9]+[dmhs]$`
	Duration *string `json:"duration,omitempty"`

	// Options are provider-specific metrics query options.
	// +kubebuilder:validation:Optional
	Options *MonitorMetricsOptions `json:"options,omitempty"`
}

func (in *MonitorMetricsQuery) Attributes() *console.MonitorMetricsQueryAttributes {
	if in == nil {
		return nil
	}

	return &console.MonitorMetricsQueryAttributes{
		Tool:     in.Tool,
		Query:    in.Query,
		Step:     in.Step,
		Duration: in.Duration,
		Options:  in.Options.Attributes(),
	}
}

// MonitorMetricsOptions are provider-specific metrics query options.
type MonitorMetricsOptions struct {
	// Azure metrics query options.
	// +kubebuilder:validation:Optional
	Azure *MonitorMetricsAzureOptions `json:"azure,omitempty"`
}

func (in *MonitorMetricsOptions) Attributes() *console.MonitorMetricsOptionsAttributes {
	if in == nil {
		return nil
	}

	var azure *console.MonitorMetricsAzureOptionsAttributes
	if in.Azure != nil {
		azure = &console.MonitorMetricsAzureOptionsAttributes{
			ResourceID:       in.Azure.ResourceID,
			MetricsNamespace: in.Azure.MetricsNamespace,
			Aggregation:      in.Azure.Aggregation,
			Filter:           in.Azure.Filter,
			OrderBy:          in.Azure.OrderBy,
			RollUpBy:         in.Azure.RollUpBy,
			MetricsEndpoint:  in.Azure.MetricsEndpoint,
		}
	}

	return &console.MonitorMetricsOptionsAttributes{Azure: azure}
}

// MonitorMetricsAzureOptions are Azure-specific metrics query options.
type MonitorMetricsAzureOptions struct {
	// ResourceID is the Azure resource ID to query metrics for.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	ResourceID *string `json:"resourceId,omitempty"`

	// MetricsNamespace is the Azure metrics namespace.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	MetricsNamespace *string `json:"metricsNamespace,omitempty"`

	// Aggregation is the Azure metrics aggregation type.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	Aggregation *string `json:"aggregation,omitempty"`

	// Filter is the Azure metrics filter expression.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	Filter *string `json:"filter,omitempty"`

	// OrderBy is the Azure metrics ordering expression.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	OrderBy *string `json:"orderBy,omitempty"`

	// RollUpBy is the Azure metrics dimension to roll up by.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	RollUpBy *string `json:"rollUpBy,omitempty"`

	// MetricsEndpoint is the Azure metrics endpoint override.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Type:=string
	MetricsEndpoint *string `json:"metricsEndpoint,omitempty"`
}
