// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: toolquery.proto

package toolquery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElasticConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Index         string                 `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElasticConnection) Reset() {
	*x = ElasticConnection{}
	mi := &file_toolquery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElasticConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticConnection) ProtoMessage() {}

func (x *ElasticConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticConnection.ProtoReflect.Descriptor instead.
func (*ElasticConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{0}
}

func (x *ElasticConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ElasticConnection) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ElasticConnection) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ElasticConnection) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

type DatadogConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          *string                `protobuf:"bytes,1,opt,name=site,proto3,oneof" json:"site,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	AppKey        *string                `protobuf:"bytes,3,opt,name=appKey,proto3,oneof" json:"appKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatadogConnection) Reset() {
	*x = DatadogConnection{}
	mi := &file_toolquery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatadogConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatadogConnection) ProtoMessage() {}

func (x *DatadogConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatadogConnection.ProtoReflect.Descriptor instead.
func (*DatadogConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{1}
}

func (x *DatadogConnection) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

func (x *DatadogConnection) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DatadogConnection) GetAppKey() string {
	if x != nil && x.AppKey != nil {
		return *x.AppKey
	}
	return ""
}

type PrometheusConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         *string                `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	TenantId      *string                `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrometheusConnection) Reset() {
	*x = PrometheusConnection{}
	mi := &file_toolquery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrometheusConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrometheusConnection) ProtoMessage() {}

func (x *PrometheusConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrometheusConnection.ProtoReflect.Descriptor instead.
func (*PrometheusConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{2}
}

func (x *PrometheusConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PrometheusConnection) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *PrometheusConnection) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *PrometheusConnection) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *PrometheusConnection) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

type LokiConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         *string                `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	TenantId      *string                `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	Username      *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LokiConnection) Reset() {
	*x = LokiConnection{}
	mi := &file_toolquery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LokiConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LokiConnection) ProtoMessage() {}

func (x *LokiConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LokiConnection.ProtoReflect.Descriptor instead.
func (*LokiConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{3}
}

func (x *LokiConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LokiConnection) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *LokiConnection) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *LokiConnection) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *LokiConnection) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type TempoConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         *string                `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	TenantId      *string                `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	Username      *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempoConnection) Reset() {
	*x = TempoConnection{}
	mi := &file_toolquery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempoConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempoConnection) ProtoMessage() {}

func (x *TempoConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempoConnection.ProtoReflect.Descriptor instead.
func (*TempoConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{4}
}

func (x *TempoConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TempoConnection) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *TempoConnection) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *TempoConnection) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *TempoConnection) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type SplunkConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         *string                `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplunkConnection) Reset() {
	*x = SplunkConnection{}
	mi := &file_toolquery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplunkConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplunkConnection) ProtoMessage() {}

func (x *SplunkConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplunkConnection.ProtoReflect.Descriptor instead.
func (*SplunkConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{5}
}

func (x *SplunkConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SplunkConnection) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *SplunkConnection) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *SplunkConnection) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type DynatraceConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PlatformToken string                 `protobuf:"bytes,2,opt,name=platformToken,proto3" json:"platformToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynatraceConnection) Reset() {
	*x = DynatraceConnection{}
	mi := &file_toolquery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynatraceConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynatraceConnection) ProtoMessage() {}

func (x *DynatraceConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynatraceConnection.ProtoReflect.Descriptor instead.
func (*DynatraceConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{6}
}

func (x *DynatraceConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DynatraceConnection) GetPlatformToken() string {
	if x != nil {
		return x.PlatformToken
	}
	return ""
}

type CloudwatchConnection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Region          string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	LogGroupNames   []string               `protobuf:"bytes,2,rep,name=log_group_names,json=logGroupNames,proto3" json:"log_group_names,omitempty"`
	AccessKeyId     *string                `protobuf:"bytes,3,opt,name=access_key_id,json=accessKeyId,proto3,oneof" json:"access_key_id,omitempty"`
	SecretAccessKey *string                `protobuf:"bytes,4,opt,name=secret_access_key,json=secretAccessKey,proto3,oneof" json:"secret_access_key,omitempty"`
	RoleArn         *string                `protobuf:"bytes,5,opt,name=role_arn,json=roleArn,proto3,oneof" json:"role_arn,omitempty"`
	ExternalId      *string                `protobuf:"bytes,6,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	RoleSessionName *string                `protobuf:"bytes,7,opt,name=role_session_name,json=roleSessionName,proto3,oneof" json:"role_session_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloudwatchConnection) Reset() {
	*x = CloudwatchConnection{}
	mi := &file_toolquery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudwatchConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudwatchConnection) ProtoMessage() {}

func (x *CloudwatchConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudwatchConnection.ProtoReflect.Descriptor instead.
func (*CloudwatchConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{7}
}

func (x *CloudwatchConnection) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CloudwatchConnection) GetLogGroupNames() []string {
	if x != nil {
		return x.LogGroupNames
	}
	return nil
}

func (x *CloudwatchConnection) GetAccessKeyId() string {
	if x != nil && x.AccessKeyId != nil {
		return *x.AccessKeyId
	}
	return ""
}

func (x *CloudwatchConnection) GetSecretAccessKey() string {
	if x != nil && x.SecretAccessKey != nil {
		return *x.SecretAccessKey
	}
	return ""
}

func (x *CloudwatchConnection) GetRoleArn() string {
	if x != nil && x.RoleArn != nil {
		return *x.RoleArn
	}
	return ""
}

func (x *CloudwatchConnection) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *CloudwatchConnection) GetRoleSessionName() string {
	if x != nil && x.RoleSessionName != nil {
		return *x.RoleSessionName
	}
	return ""
}

type AzureConnection struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId       string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret   string                 `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AzureConnection) Reset() {
	*x = AzureConnection{}
	mi := &file_toolquery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureConnection) ProtoMessage() {}

func (x *AzureConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureConnection.ProtoReflect.Descriptor instead.
func (*AzureConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{8}
}

func (x *AzureConnection) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AzureConnection) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AzureConnection) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AzureConnection) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type ToolConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Connection:
	//
	//	*ToolConnection_Elastic
	//	*ToolConnection_Datadog
	//	*ToolConnection_Prometheus
	//	*ToolConnection_Loki
	//	*ToolConnection_Tempo
	//	*ToolConnection_Splunk
	//	*ToolConnection_Dynatrace
	//	*ToolConnection_Cloudwatch
	//	*ToolConnection_Azure
	Connection    isToolConnection_Connection `protobuf_oneof:"connection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolConnection) Reset() {
	*x = ToolConnection{}
	mi := &file_toolquery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolConnection) ProtoMessage() {}

func (x *ToolConnection) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolConnection.ProtoReflect.Descriptor instead.
func (*ToolConnection) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{9}
}

func (x *ToolConnection) GetConnection() isToolConnection_Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ToolConnection) GetElastic() *ElasticConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Elastic); ok {
			return x.Elastic
		}
	}
	return nil
}

func (x *ToolConnection) GetDatadog() *DatadogConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Datadog); ok {
			return x.Datadog
		}
	}
	return nil
}

func (x *ToolConnection) GetPrometheus() *PrometheusConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Prometheus); ok {
			return x.Prometheus
		}
	}
	return nil
}

func (x *ToolConnection) GetLoki() *LokiConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Loki); ok {
			return x.Loki
		}
	}
	return nil
}

func (x *ToolConnection) GetTempo() *TempoConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Tempo); ok {
			return x.Tempo
		}
	}
	return nil
}

func (x *ToolConnection) GetSplunk() *SplunkConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Splunk); ok {
			return x.Splunk
		}
	}
	return nil
}

func (x *ToolConnection) GetDynatrace() *DynatraceConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Dynatrace); ok {
			return x.Dynatrace
		}
	}
	return nil
}

func (x *ToolConnection) GetCloudwatch() *CloudwatchConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Cloudwatch); ok {
			return x.Cloudwatch
		}
	}
	return nil
}

func (x *ToolConnection) GetAzure() *AzureConnection {
	if x != nil {
		if x, ok := x.Connection.(*ToolConnection_Azure); ok {
			return x.Azure
		}
	}
	return nil
}

type isToolConnection_Connection interface {
	isToolConnection_Connection()
}

type ToolConnection_Elastic struct {
	Elastic *ElasticConnection `protobuf:"bytes,1,opt,name=elastic,proto3,oneof"`
}

type ToolConnection_Datadog struct {
	Datadog *DatadogConnection `protobuf:"bytes,2,opt,name=datadog,proto3,oneof"`
}

type ToolConnection_Prometheus struct {
	Prometheus *PrometheusConnection `protobuf:"bytes,3,opt,name=prometheus,proto3,oneof"`
}

type ToolConnection_Loki struct {
	Loki *LokiConnection `protobuf:"bytes,4,opt,name=loki,proto3,oneof"`
}

type ToolConnection_Tempo struct {
	Tempo *TempoConnection `protobuf:"bytes,5,opt,name=tempo,proto3,oneof"`
}

type ToolConnection_Splunk struct {
	Splunk *SplunkConnection `protobuf:"bytes,6,opt,name=splunk,proto3,oneof"`
}

type ToolConnection_Dynatrace struct {
	Dynatrace *DynatraceConnection `protobuf:"bytes,7,opt,name=dynatrace,proto3,oneof"`
}

type ToolConnection_Cloudwatch struct {
	Cloudwatch *CloudwatchConnection `protobuf:"bytes,8,opt,name=cloudwatch,proto3,oneof"`
}

type ToolConnection_Azure struct {
	Azure *AzureConnection `protobuf:"bytes,9,opt,name=azure,proto3,oneof"`
}

func (*ToolConnection_Elastic) isToolConnection_Connection() {}

func (*ToolConnection_Datadog) isToolConnection_Connection() {}

func (*ToolConnection_Prometheus) isToolConnection_Connection() {}

func (*ToolConnection_Loki) isToolConnection_Connection() {}

func (*ToolConnection_Tempo) isToolConnection_Connection() {}

func (*ToolConnection_Splunk) isToolConnection_Connection() {}

func (*ToolConnection_Dynatrace) isToolConnection_Connection() {}

func (*ToolConnection_Cloudwatch) isToolConnection_Connection() {}

func (*ToolConnection_Azure) isToolConnection_Connection() {}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_toolquery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{10}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type MetricsQueryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *ToolConnection        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Step          *string                `protobuf:"bytes,4,opt,name=step,proto3,oneof" json:"step,omitempty"`
	Options       *MetricsOptions        `protobuf:"bytes,5,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryInput) Reset() {
	*x = MetricsQueryInput{}
	mi := &file_toolquery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryInput) ProtoMessage() {}

func (x *MetricsQueryInput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryInput.ProtoReflect.Descriptor instead.
func (*MetricsQueryInput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsQueryInput) GetConnection() *ToolConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *MetricsQueryInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MetricsQueryInput) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *MetricsQueryInput) GetStep() string {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return ""
}

func (x *MetricsQueryInput) GetOptions() *MetricsOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type MetricsOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Azure         *AzureMetricsOptions   `protobuf:"bytes,1,opt,name=azure,proto3,oneof" json:"azure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsOptions) Reset() {
	*x = MetricsOptions{}
	mi := &file_toolquery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsOptions) ProtoMessage() {}

func (x *MetricsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsOptions.ProtoReflect.Descriptor instead.
func (*MetricsOptions) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{12}
}

func (x *MetricsOptions) GetAzure() *AzureMetricsOptions {
	if x != nil {
		return x.Azure
	}
	return nil
}

type AzureMetricsOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceId       string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	MetricsNamespace string                 `protobuf:"bytes,2,opt,name=metrics_namespace,json=metricsNamespace,proto3" json:"metrics_namespace,omitempty"`
	Aggregation      *string                `protobuf:"bytes,3,opt,name=aggregation,proto3,oneof" json:"aggregation,omitempty"`
	Filter           *string                `protobuf:"bytes,4,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	OrderBy          *string                `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	RollUpBy         *string                `protobuf:"bytes,6,opt,name=roll_up_by,json=rollUpBy,proto3,oneof" json:"roll_up_by,omitempty"`
	MetricsEndpoint  *string                `protobuf:"bytes,7,opt,name=metrics_endpoint,json=metricsEndpoint,proto3,oneof" json:"metrics_endpoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AzureMetricsOptions) Reset() {
	*x = AzureMetricsOptions{}
	mi := &file_toolquery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMetricsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMetricsOptions) ProtoMessage() {}

func (x *AzureMetricsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMetricsOptions.ProtoReflect.Descriptor instead.
func (*AzureMetricsOptions) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{13}
}

func (x *AzureMetricsOptions) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AzureMetricsOptions) GetMetricsNamespace() string {
	if x != nil {
		return x.MetricsNamespace
	}
	return ""
}

func (x *AzureMetricsOptions) GetAggregation() string {
	if x != nil && x.Aggregation != nil {
		return *x.Aggregation
	}
	return ""
}

func (x *AzureMetricsOptions) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *AzureMetricsOptions) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *AzureMetricsOptions) GetRollUpBy() string {
	if x != nil && x.RollUpBy != nil {
		return *x.RollUpBy
	}
	return ""
}

func (x *AzureMetricsOptions) GetMetricsEndpoint() string {
	if x != nil && x.MetricsEndpoint != nil {
		return *x.MetricsEndpoint
	}
	return ""
}

type LogsQueryFacet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsQueryFacet) Reset() {
	*x = LogsQueryFacet{}
	mi := &file_toolquery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsQueryFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsQueryFacet) ProtoMessage() {}

func (x *LogsQueryFacet) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsQueryFacet.ProtoReflect.Descriptor instead.
func (*LogsQueryFacet) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{14}
}

func (x *LogsQueryFacet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogsQueryFacet) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LogsQueryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *ToolConnection        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Limit         *int32                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Facets        []*LogsQueryFacet      `protobuf:"bytes,5,rep,name=facets,proto3" json:"facets,omitempty"`
	Options       *LogsOptions           `protobuf:"bytes,6,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsQueryInput) Reset() {
	*x = LogsQueryInput{}
	mi := &file_toolquery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsQueryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsQueryInput) ProtoMessage() {}

func (x *LogsQueryInput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsQueryInput.ProtoReflect.Descriptor instead.
func (*LogsQueryInput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{15}
}

func (x *LogsQueryInput) GetConnection() *ToolConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *LogsQueryInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *LogsQueryInput) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *LogsQueryInput) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *LogsQueryInput) GetFacets() []*LogsQueryFacet {
	if x != nil {
		return x.Facets
	}
	return nil
}

func (x *LogsQueryInput) GetOptions() *LogsOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type LogsOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Azure         *AzureLogsOptions      `protobuf:"bytes,1,opt,name=azure,proto3,oneof" json:"azure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsOptions) Reset() {
	*x = LogsOptions{}
	mi := &file_toolquery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsOptions) ProtoMessage() {}

func (x *LogsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsOptions.ProtoReflect.Descriptor instead.
func (*LogsOptions) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{16}
}

func (x *LogsOptions) GetAzure() *AzureLogsOptions {
	if x != nil {
		return x.Azure
	}
	return nil
}

type AzureLogsOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureLogsOptions) Reset() {
	*x = AzureLogsOptions{}
	mi := &file_toolquery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureLogsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureLogsOptions) ProtoMessage() {}

func (x *AzureLogsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureLogsOptions.ProtoReflect.Descriptor instead.
func (*AzureLogsOptions) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{17}
}

func (x *AzureLogsOptions) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type TracesQueryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *ToolConnection        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Limit         *int32                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracesQueryInput) Reset() {
	*x = TracesQueryInput{}
	mi := &file_toolquery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracesQueryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracesQueryInput) ProtoMessage() {}

func (x *TracesQueryInput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracesQueryInput.ProtoReflect.Descriptor instead.
func (*TracesQueryInput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{18}
}

func (x *TracesQueryInput) GetConnection() *ToolConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *TracesQueryInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TracesQueryInput) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *TracesQueryInput) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_toolquery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{19}
}

func (x *MetricPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricsQueryOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricPoint         `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryOutput) Reset() {
	*x = MetricsQueryOutput{}
	mi := &file_toolquery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryOutput) ProtoMessage() {}

func (x *MetricsQueryOutput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryOutput.ProtoReflect.Descriptor instead.
func (*MetricsQueryOutput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{20}
}

func (x *MetricsQueryOutput) GetMetrics() []*MetricPoint {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsSearchInput struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Connection *ToolConnection        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	// Query string used to search for metric series or names.
	// Semantics are provider-specific but typically support substring or
	// pattern-based matching on metric names and associated labels.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Maximum number of results to return. If not set or zero, a
	// provider-specific default will be used.
	Limit         *int64                `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Options       *MetricsSearchOptions `protobuf:"bytes,4,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSearchInput) Reset() {
	*x = MetricsSearchInput{}
	mi := &file_toolquery_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSearchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSearchInput) ProtoMessage() {}

func (x *MetricsSearchInput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSearchInput.ProtoReflect.Descriptor instead.
func (*MetricsSearchInput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{21}
}

func (x *MetricsSearchInput) GetConnection() *ToolConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *MetricsSearchInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MetricsSearchInput) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *MetricsSearchInput) GetOptions() *MetricsSearchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type MetricsSearchOptions struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Azure         *AzureMetricsSearchOptions `protobuf:"bytes,1,opt,name=azure,proto3,oneof" json:"azure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSearchOptions) Reset() {
	*x = MetricsSearchOptions{}
	mi := &file_toolquery_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSearchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSearchOptions) ProtoMessage() {}

func (x *MetricsSearchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSearchOptions.ProtoReflect.Descriptor instead.
func (*MetricsSearchOptions) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{22}
}

func (x *MetricsSearchOptions) GetAzure() *AzureMetricsSearchOptions {
	if x != nil {
		return x.Azure
	}
	return nil
}

type AzureMetricsSearchOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureMetricsSearchOptions) Reset() {
	*x = AzureMetricsSearchOptions{}
	mi := &file_toolquery_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMetricsSearchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMetricsSearchOptions) ProtoMessage() {}

func (x *AzureMetricsSearchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMetricsSearchOptions.ProtoReflect.Descriptor instead.
func (*AzureMetricsSearchOptions) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{23}
}

func (x *AzureMetricsSearchOptions) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type MetricsSearchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the metric or series as returned by the provider.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSearchResult) Reset() {
	*x = MetricsSearchResult{}
	mi := &file_toolquery_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSearchResult) ProtoMessage() {}

func (x *MetricsSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSearchResult.ProtoReflect.Descriptor instead.
func (*MetricsSearchResult) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{24}
}

func (x *MetricsSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MetricsSearchOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricsSearchResult `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSearchOutput) Reset() {
	*x = MetricsSearchOutput{}
	mi := &file_toolquery_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSearchOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSearchOutput) ProtoMessage() {}

func (x *MetricsSearchOutput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSearchOutput.ProtoReflect.Descriptor instead.
func (*MetricsSearchOutput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{25}
}

func (x *MetricsSearchOutput) GetMetrics() []*MetricsSearchResult {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_toolquery_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{26}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type LogsQueryOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsQueryOutput) Reset() {
	*x = LogsQueryOutput{}
	mi := &file_toolquery_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsQueryOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsQueryOutput) ProtoMessage() {}

func (x *LogsQueryOutput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsQueryOutput.ProtoReflect.Descriptor instead.
func (*LogsQueryOutput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{27}
}

func (x *LogsQueryOutput) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type TraceSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Service       string                 `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceSpan) Reset() {
	*x = TraceSpan{}
	mi := &file_toolquery_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceSpan) ProtoMessage() {}

func (x *TraceSpan) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceSpan.ProtoReflect.Descriptor instead.
func (*TraceSpan) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{28}
}

func (x *TraceSpan) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceSpan) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceSpan) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *TraceSpan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TraceSpan) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TraceSpan) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TraceSpan) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *TraceSpan) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TracesQueryOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*TraceSpan           `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracesQueryOutput) Reset() {
	*x = TracesQueryOutput{}
	mi := &file_toolquery_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracesQueryOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracesQueryOutput) ProtoMessage() {}

func (x *TracesQueryOutput) ProtoReflect() protoreflect.Message {
	mi := &file_toolquery_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracesQueryOutput.ProtoReflect.Descriptor instead.
func (*TracesQueryOutput) Descriptor() ([]byte, []int) {
	return file_toolquery_proto_rawDescGZIP(), []int{29}
}

func (x *TracesQueryOutput) GetSpans() []*TraceSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

var File_toolquery_proto protoreflect.FileDescriptor

const file_toolquery_proto_rawDesc = "" +
	"\n" +
	"\x0ftoolquery.proto\x12\ttoolquery\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n" +
	"\x11ElasticConnection\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05index\x18\x04 \x01(\tR\x05index\"u\n" +
	"\x11DatadogConnection\x12\x17\n" +
	"\x04site\x18\x01 \x01(\tH\x00R\x04site\x88\x01\x01\x12\x16\n" +
	"\x06apiKey\x18\x02 \x01(\tR\x06apiKey\x12\x1b\n" +
	"\x06appKey\x18\x03 \x01(\tH\x01R\x06appKey\x88\x01\x01B\a\n" +
	"\x05_siteB\t\n" +
	"\a_appKey\"\xd9\x01\n" +
	"\x14PrometheusConnection\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x01R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x02R\bpassword\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x05 \x01(\tH\x03R\btenantId\x88\x01\x01B\b\n" +
	"\x06_tokenB\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\f\n" +
	"\n" +
	"_tenant_id\"\xd3\x01\n" +
	"\x0eLokiConnection\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x03 \x01(\tH\x01R\btenantId\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x03R\bpassword\x88\x01\x01B\b\n" +
	"\x06_tokenB\f\n" +
	"\n" +
	"_tenant_idB\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"\xd4\x01\n" +
	"\x0fTempoConnection\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x03 \x01(\tH\x01R\btenantId\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x03R\bpassword\x88\x01\x01B\b\n" +
	"\x06_tokenB\f\n" +
	"\n" +
	"_tenant_idB\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"\xa5\x01\n" +
	"\x10SplunkConnection\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x01R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x02R\bpassword\x88\x01\x01B\b\n" +
	"\x06_tokenB\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"M\n" +
	"\x13DynatraceConnection\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12$\n" +
	"\rplatformToken\x18\x02 \x01(\tR\rplatformToken\"\x82\x03\n" +
	"\x14CloudwatchConnection\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12&\n" +
	"\x0flog_group_names\x18\x02 \x03(\tR\rlogGroupNames\x12'\n" +
	"\raccess_key_id\x18\x03 \x01(\tH\x00R\vaccessKeyId\x88\x01\x01\x12/\n" +
	"\x11secret_access_key\x18\x04 \x01(\tH\x01R\x0fsecretAccessKey\x88\x01\x01\x12\x1e\n" +
	"\brole_arn\x18\x05 \x01(\tH\x02R\aroleArn\x88\x01\x01\x12$\n" +
	"\vexternal_id\x18\x06 \x01(\tH\x03R\n" +
	"externalId\x88\x01\x01\x12/\n" +
	"\x11role_session_name\x18\a \x01(\tH\x04R\x0froleSessionName\x88\x01\x01B\x10\n" +
	"\x0e_access_key_idB\x14\n" +
	"\x12_secret_access_keyB\v\n" +
	"\t_role_arnB\x0e\n" +
	"\f_external_idB\x14\n" +
	"\x12_role_session_name\"\x99\x01\n" +
	"\x0fAzureConnection\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x04 \x01(\tR\fclientSecret\"\xa8\x04\n" +
	"\x0eToolConnection\x128\n" +
	"\aelastic\x18\x01 \x01(\v2\x1c.toolquery.ElasticConnectionH\x00R\aelastic\x128\n" +
	"\adatadog\x18\x02 \x01(\v2\x1c.toolquery.DatadogConnectionH\x00R\adatadog\x12A\n" +
	"\n" +
	"prometheus\x18\x03 \x01(\v2\x1f.toolquery.PrometheusConnectionH\x00R\n" +
	"prometheus\x12/\n" +
	"\x04loki\x18\x04 \x01(\v2\x19.toolquery.LokiConnectionH\x00R\x04loki\x122\n" +
	"\x05tempo\x18\x05 \x01(\v2\x1a.toolquery.TempoConnectionH\x00R\x05tempo\x125\n" +
	"\x06splunk\x18\x06 \x01(\v2\x1b.toolquery.SplunkConnectionH\x00R\x06splunk\x12>\n" +
	"\tdynatrace\x18\a \x01(\v2\x1e.toolquery.DynatraceConnectionH\x00R\tdynatrace\x12A\n" +
	"\n" +
	"cloudwatch\x18\b \x01(\v2\x1f.toolquery.CloudwatchConnectionH\x00R\n" +
	"cloudwatch\x122\n" +
	"\x05azure\x18\t \x01(\v2\x1a.toolquery.AzureConnectionH\x00R\x05azureB\f\n" +
	"\n" +
	"connection\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xf8\x01\n" +
	"\x11MetricsQueryInput\x129\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x19.toolquery.ToolConnectionR\n" +
	"connection\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12*\n" +
	"\x05range\x18\x03 \x01(\v2\x14.toolquery.TimeRangeR\x05range\x12\x17\n" +
	"\x04step\x18\x04 \x01(\tH\x00R\x04step\x88\x01\x01\x128\n" +
	"\aoptions\x18\x05 \x01(\v2\x19.toolquery.MetricsOptionsH\x01R\aoptions\x88\x01\x01B\a\n" +
	"\x05_stepB\n" +
	"\n" +
	"\b_options\"U\n" +
	"\x0eMetricsOptions\x129\n" +
	"\x05azure\x18\x01 \x01(\v2\x1e.toolquery.AzureMetricsOptionsH\x00R\x05azure\x88\x01\x01B\b\n" +
	"\x06_azure\"\xe6\x02\n" +
	"\x13AzureMetricsOptions\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12+\n" +
	"\x11metrics_namespace\x18\x02 \x01(\tR\x10metricsNamespace\x12%\n" +
	"\vaggregation\x18\x03 \x01(\tH\x00R\vaggregation\x88\x01\x01\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tH\x01R\x06filter\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tH\x02R\aorderBy\x88\x01\x01\x12!\n" +
	"\n" +
	"roll_up_by\x18\x06 \x01(\tH\x03R\brollUpBy\x88\x01\x01\x12.\n" +
	"\x10metrics_endpoint\x18\a \x01(\tH\x04R\x0fmetricsEndpoint\x88\x01\x01B\x0e\n" +
	"\f_aggregationB\t\n" +
	"\a_filterB\v\n" +
	"\t_order_byB\r\n" +
	"\v_roll_up_byB\x13\n" +
	"\x11_metrics_endpoint\":\n" +
	"\x0eLogsQueryFacet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa8\x02\n" +
	"\x0eLogsQueryInput\x129\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x19.toolquery.ToolConnectionR\n" +
	"connection\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12*\n" +
	"\x05range\x18\x03 \x01(\v2\x14.toolquery.TimeRangeR\x05range\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x00R\x05limit\x88\x01\x01\x121\n" +
	"\x06facets\x18\x05 \x03(\v2\x19.toolquery.LogsQueryFacetR\x06facets\x125\n" +
	"\aoptions\x18\x06 \x01(\v2\x16.toolquery.LogsOptionsH\x01R\aoptions\x88\x01\x01B\b\n" +
	"\x06_limitB\n" +
	"\n" +
	"\b_options\"O\n" +
	"\vLogsOptions\x126\n" +
	"\x05azure\x18\x01 \x01(\v2\x1b.toolquery.AzureLogsOptionsH\x00R\x05azure\x88\x01\x01B\b\n" +
	"\x06_azure\"3\n" +
	"\x10AzureLogsOptions\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"\xb4\x01\n" +
	"\x10TracesQueryInput\x129\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x19.toolquery.ToolConnectionR\n" +
	"connection\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12*\n" +
	"\x05range\x18\x03 \x01(\v2\x14.toolquery.TimeRangeR\x05range\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"\xe8\x01\n" +
	"\vMetricPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12:\n" +
	"\x06labels\x18\x04 \x03(\v2\".toolquery.MetricPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x12MetricsQueryOutput\x120\n" +
	"\ametrics\x18\x01 \x03(\v2\x16.toolquery.MetricPointR\ametrics\"\xd6\x01\n" +
	"\x12MetricsSearchInput\x129\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x19.toolquery.ToolConnectionR\n" +
	"connection\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12>\n" +
	"\aoptions\x18\x04 \x01(\v2\x1f.toolquery.MetricsSearchOptionsH\x01R\aoptions\x88\x01\x01B\b\n" +
	"\x06_limitB\n" +
	"\n" +
	"\b_options\"a\n" +
	"\x14MetricsSearchOptions\x12?\n" +
	"\x05azure\x18\x01 \x01(\v2$.toolquery.AzureMetricsSearchOptionsH\x00R\x05azure\x88\x01\x01B\b\n" +
	"\x06_azure\"<\n" +
	"\x19AzureMetricsSearchOptions\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\")\n" +
	"\x13MetricsSearchResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"O\n" +
	"\x13MetricsSearchOutput\x128\n" +
	"\ametrics\x18\x01 \x03(\v2\x1e.toolquery.MetricsSearchResultR\ametrics\"\xd2\x01\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x06labels\x18\x03 \x03(\v2\x1f.toolquery.LogEntry.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0fLogsQueryOutput\x12'\n" +
	"\x04logs\x18\x01 \x03(\v2\x13.toolquery.LogEntryR\x04logs\"\xd7\x02\n" +
	"\tTraceSpan\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\aservice\x18\x05 \x01(\tR\aservice\x120\n" +
	"\x05start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x122\n" +
	"\x04tags\x18\b \x03(\v2\x1e.toolquery.TraceSpan.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x11TracesQueryOutput\x12*\n" +
	"\x05spans\x18\x01 \x03(\v2\x14.toolquery.TraceSpanR\x05spans2\xaf\x02\n" +
	"\tToolQuery\x12H\n" +
	"\aMetrics\x12\x1c.toolquery.MetricsQueryInput\x1a\x1d.toolquery.MetricsQueryOutput\"\x00\x12P\n" +
	"\rMetricsSearch\x12\x1d.toolquery.MetricsSearchInput\x1a\x1e.toolquery.MetricsSearchOutput\"\x00\x12?\n" +
	"\x04Logs\x12\x19.toolquery.LogsQueryInput\x1a\x1a.toolquery.LogsQueryOutput\"\x00\x12E\n" +
	"\x06Traces\x12\x1b.toolquery.TracesQueryInput\x1a\x1c.toolquery.TracesQueryOutput\"\x00B\x1aZ\x18internal/proto/toolqueryb\x06proto3"

var (
	file_toolquery_proto_rawDescOnce sync.Once
	file_toolquery_proto_rawDescData []byte
)

func file_toolquery_proto_rawDescGZIP() []byte {
	file_toolquery_proto_rawDescOnce.Do(func() {
		file_toolquery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_toolquery_proto_rawDesc), len(file_toolquery_proto_rawDesc)))
	})
	return file_toolquery_proto_rawDescData
}

var file_toolquery_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_toolquery_proto_goTypes = []any{
	(*ElasticConnection)(nil),         // 0: toolquery.ElasticConnection
	(*DatadogConnection)(nil),         // 1: toolquery.DatadogConnection
	(*PrometheusConnection)(nil),      // 2: toolquery.PrometheusConnection
	(*LokiConnection)(nil),            // 3: toolquery.LokiConnection
	(*TempoConnection)(nil),           // 4: toolquery.TempoConnection
	(*SplunkConnection)(nil),          // 5: toolquery.SplunkConnection
	(*DynatraceConnection)(nil),       // 6: toolquery.DynatraceConnection
	(*CloudwatchConnection)(nil),      // 7: toolquery.CloudwatchConnection
	(*AzureConnection)(nil),           // 8: toolquery.AzureConnection
	(*ToolConnection)(nil),            // 9: toolquery.ToolConnection
	(*TimeRange)(nil),                 // 10: toolquery.TimeRange
	(*MetricsQueryInput)(nil),         // 11: toolquery.MetricsQueryInput
	(*MetricsOptions)(nil),            // 12: toolquery.MetricsOptions
	(*AzureMetricsOptions)(nil),       // 13: toolquery.AzureMetricsOptions
	(*LogsQueryFacet)(nil),            // 14: toolquery.LogsQueryFacet
	(*LogsQueryInput)(nil),            // 15: toolquery.LogsQueryInput
	(*LogsOptions)(nil),               // 16: toolquery.LogsOptions
	(*AzureLogsOptions)(nil),          // 17: toolquery.AzureLogsOptions
	(*TracesQueryInput)(nil),          // 18: toolquery.TracesQueryInput
	(*MetricPoint)(nil),               // 19: toolquery.MetricPoint
	(*MetricsQueryOutput)(nil),        // 20: toolquery.MetricsQueryOutput
	(*MetricsSearchInput)(nil),        // 21: toolquery.MetricsSearchInput
	(*MetricsSearchOptions)(nil),      // 22: toolquery.MetricsSearchOptions
	(*AzureMetricsSearchOptions)(nil), // 23: toolquery.AzureMetricsSearchOptions
	(*MetricsSearchResult)(nil),       // 24: toolquery.MetricsSearchResult
	(*MetricsSearchOutput)(nil),       // 25: toolquery.MetricsSearchOutput
	(*LogEntry)(nil),                  // 26: toolquery.LogEntry
	(*LogsQueryOutput)(nil),           // 27: toolquery.LogsQueryOutput
	(*TraceSpan)(nil),                 // 28: toolquery.TraceSpan
	(*TracesQueryOutput)(nil),         // 29: toolquery.TracesQueryOutput
	nil,                               // 30: toolquery.MetricPoint.LabelsEntry
	nil,                               // 31: toolquery.LogEntry.LabelsEntry
	nil,                               // 32: toolquery.TraceSpan.TagsEntry
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
}
var file_toolquery_proto_depIdxs = []int32{
	0,  // 0: toolquery.ToolConnection.elastic:type_name -> toolquery.ElasticConnection
	1,  // 1: toolquery.ToolConnection.datadog:type_name -> toolquery.DatadogConnection
	2,  // 2: toolquery.ToolConnection.prometheus:type_name -> toolquery.PrometheusConnection
	3,  // 3: toolquery.ToolConnection.loki:type_name -> toolquery.LokiConnection
	4,  // 4: toolquery.ToolConnection.tempo:type_name -> toolquery.TempoConnection
	5,  // 5: toolquery.ToolConnection.splunk:type_name -> toolquery.SplunkConnection
	6,  // 6: toolquery.ToolConnection.dynatrace:type_name -> toolquery.DynatraceConnection
	7,  // 7: toolquery.ToolConnection.cloudwatch:type_name -> toolquery.CloudwatchConnection
	8,  // 8: toolquery.ToolConnection.azure:type_name -> toolquery.AzureConnection
	33, // 9: toolquery.TimeRange.start:type_name -> google.protobuf.Timestamp
	33, // 10: toolquery.TimeRange.end:type_name -> google.protobuf.Timestamp
	9,  // 11: toolquery.MetricsQueryInput.connection:type_name -> toolquery.ToolConnection
	10, // 12: toolquery.MetricsQueryInput.range:type_name -> toolquery.TimeRange
	12, // 13: toolquery.MetricsQueryInput.options:type_name -> toolquery.MetricsOptions
	13, // 14: toolquery.MetricsOptions.azure:type_name -> toolquery.AzureMetricsOptions
	9,  // 15: toolquery.LogsQueryInput.connection:type_name -> toolquery.ToolConnection
	10, // 16: toolquery.LogsQueryInput.range:type_name -> toolquery.TimeRange
	14, // 17: toolquery.LogsQueryInput.facets:type_name -> toolquery.LogsQueryFacet
	16, // 18: toolquery.LogsQueryInput.options:type_name -> toolquery.LogsOptions
	17, // 19: toolquery.LogsOptions.azure:type_name -> toolquery.AzureLogsOptions
	9,  // 20: toolquery.TracesQueryInput.connection:type_name -> toolquery.ToolConnection
	10, // 21: toolquery.TracesQueryInput.range:type_name -> toolquery.TimeRange
	33, // 22: toolquery.MetricPoint.timestamp:type_name -> google.protobuf.Timestamp
	30, // 23: toolquery.MetricPoint.labels:type_name -> toolquery.MetricPoint.LabelsEntry
	19, // 24: toolquery.MetricsQueryOutput.metrics:type_name -> toolquery.MetricPoint
	9,  // 25: toolquery.MetricsSearchInput.connection:type_name -> toolquery.ToolConnection
	22, // 26: toolquery.MetricsSearchInput.options:type_name -> toolquery.MetricsSearchOptions
	23, // 27: toolquery.MetricsSearchOptions.azure:type_name -> toolquery.AzureMetricsSearchOptions
	24, // 28: toolquery.MetricsSearchOutput.metrics:type_name -> toolquery.MetricsSearchResult
	33, // 29: toolquery.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	31, // 30: toolquery.LogEntry.labels:type_name -> toolquery.LogEntry.LabelsEntry
	26, // 31: toolquery.LogsQueryOutput.logs:type_name -> toolquery.LogEntry
	33, // 32: toolquery.TraceSpan.start:type_name -> google.protobuf.Timestamp
	33, // 33: toolquery.TraceSpan.end:type_name -> google.protobuf.Timestamp
	32, // 34: toolquery.TraceSpan.tags:type_name -> toolquery.TraceSpan.TagsEntry
	28, // 35: toolquery.TracesQueryOutput.spans:type_name -> toolquery.TraceSpan
	11, // 36: toolquery.ToolQuery.Metrics:input_type -> toolquery.MetricsQueryInput
	21, // 37: toolquery.ToolQuery.MetricsSearch:input_type -> toolquery.MetricsSearchInput
	15, // 38: toolquery.ToolQuery.Logs:input_type -> toolquery.LogsQueryInput
	18, // 39: toolquery.ToolQuery.Traces:input_type -> toolquery.TracesQueryInput
	20, // 40: toolquery.ToolQuery.Metrics:output_type -> toolquery.MetricsQueryOutput
	25, // 41: toolquery.ToolQuery.MetricsSearch:output_type -> toolquery.MetricsSearchOutput
	27, // 42: toolquery.ToolQuery.Logs:output_type -> toolquery.LogsQueryOutput
	29, // 43: toolquery.ToolQuery.Traces:output_type -> toolquery.TracesQueryOutput
	40, // [40:44] is the sub-list for method output_type
	36, // [36:40] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_toolquery_proto_init() }
func file_toolquery_proto_init() {
	if File_toolquery_proto != nil {
		return
	}
	file_toolquery_proto_msgTypes[1].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[2].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[3].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[4].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[5].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[7].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[9].OneofWrappers = []any{
		(*ToolConnection_Elastic)(nil),
		(*ToolConnection_Datadog)(nil),
		(*ToolConnection_Prometheus)(nil),
		(*ToolConnection_Loki)(nil),
		(*ToolConnection_Tempo)(nil),
		(*ToolConnection_Splunk)(nil),
		(*ToolConnection_Dynatrace)(nil),
		(*ToolConnection_Cloudwatch)(nil),
		(*ToolConnection_Azure)(nil),
	}
	file_toolquery_proto_msgTypes[11].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[12].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[13].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[15].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[16].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[18].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[21].OneofWrappers = []any{}
	file_toolquery_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_toolquery_proto_rawDesc), len(file_toolquery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_toolquery_proto_goTypes,
		DependencyIndexes: file_toolquery_proto_depIdxs,
		MessageInfos:      file_toolquery_proto_msgTypes,
	}.Build()
	File_toolquery_proto = out.File
	file_toolquery_proto_goTypes = nil
	file_toolquery_proto_depIdxs = nil
}
