apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kas.configMapName" . }}
  labels:
    {{- include "kas.labels" . | nindent 4 }}
data:
  config.yaml: |
    agent:
      listen:
        address: ":{{ .Values.kas.service.agentPort }}"
        websocket: true
      kubernetes_api:
        listen:
          address: ":{{ .Values.kas.service.kubernetesApiPort }}"
        url_path_prefix: "{{ .Values.kas.ingress.kubernetesApiPath }}"
        jwt_authentication_secret_file: "/etc/kas/jwt_secret"
    observability:
      listen:
        address: ":{{ .Values.kas.service.observabilityPort }}"
      logging:
        level: {{ .Values.kas.logging.level }}
    redis:
      server:
        address: "{{ printf "%s-master" (include "redis.fullname" .) }}:{{ .Values.kas.redis.master.service.ports.redis }}"
      key_prefix: {{ include "kas.name" . }}
      password_file: "/etc/kas/redis_server_secret"
    api:
      listen:
        address: ":{{ .Values.kas.service.apiInternalPort }}"
        authentication_secret_file: "/etc/kas/.api_secret"
    private_api:
      listen:
        address: ":{{ .Values.kas.service.privateApiPort }}"
        authentication_secret_file: "/etc/kas/.privateapi_secret"
    plural_url: "https://{{ .Values.kas.consoleUrl }}/gql"
