{{/*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/* vim: set filetype=mustache: */}}

{{/*
Create a dedicated fully qualified name for Redis resources.
*/}}
{{- define "redis.fullname" -}}
{{- $baseName := include "console.fullname" . | trunc 57 | trimSuffix "-" -}}
{{- printf "%s-redis" $baseName | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Return the proper Redis image name
*/}}
{{- define "redis.image" -}}
{{ include "common.images.image" (dict "imageRoot" .Values.kas.redis.image "global" .Values.kas.redis.global) }}
{{- end -}}

{{/*
Return the proper image name (for the metrics image)
*/}}
{{- define "redis.metrics.image" -}}
{{ include "common.images.image" (dict "imageRoot" .Values.kas.redis.metrics.image "global" .Values.kas.redis.global) }}
{{- end -}}

{{/*
Return the proper image name (for the init container volume-permissions image)
*/}}
{{- define "redis.volumePermissions.image" -}}
{{ include "common.images.image" (dict "imageRoot" .Values.kas.redis.volumePermissions.image "global" .Values.kas.redis.global) }}
{{- end -}}

{{/*
Return sysctl image
*/}}
{{- define "redis.sysctl.image" -}}
{{ include "common.images.image" (dict "imageRoot" .Values.kas.redis.sysctl.image "global" .Values.kas.redis.global) }}
{{- end -}}

{{/*
Return the proper Docker Image Registry Secret Names
*/}}
{{- define "redis.imagePullSecrets" -}}
{{- include "common.images.renderPullSecrets" (dict "images" (list .Values.kas.redis.image .Values.kas.redis.metrics.image .Values.kas.redis.volumePermissions.image .Values.kas.redis.sysctl.image) "context" $) -}}
{{- end -}}

{{/*
Return true if a TLS secret object should be created
*/}}
{{- define "redis.createTlsSecret" -}}
{{- if and .Values.kas.redis.tls.enabled .Values.kas.redis.tls.autoGenerated (and (not .Values.kas.redis.tls.existingSecret) (not .Values.kas.redis.tls.certificatesSecret)) }}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Return the secret containing Redis TLS certificates
*/}}
{{- define "redis.tlsSecretName" -}}
{{- $secretName := coalesce .Values.kas.redis.tls.existingSecret .Values.kas.redis.tls.certificatesSecret -}}
{{- if $secretName -}}
    {{- printf "%s" (tpl $secretName $) -}}
{{- else -}}
    {{- printf "%s-crt" (include "redis.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Return the path to the cert file.
*/}}
{{- define "redis.tlsCert" -}}
{{- if (include "redis.createTlsSecret" . ) -}}
    {{- printf "/opt/bitnami/redis/certs/%s" "tls.crt" -}}
{{- else -}}
    {{- required "Certificate filename is required when TLS in enabled" .Values.kas.redis.tls.certFilename | printf "/opt/bitnami/redis/certs/%s" -}}
{{- end -}}
{{- end -}}

{{/*
Return the path to the cert key file.
*/}}
{{- define "redis.tlsCertKey" -}}
{{- if (include "redis.createTlsSecret" . ) -}}
    {{- printf "/opt/bitnami/redis/certs/%s" "tls.key" -}}
{{- else -}}
    {{- required "Certificate Key filename is required when TLS in enabled" .Values.kas.redis.tls.certKeyFilename | printf "/opt/bitnami/redis/certs/%s" -}}
{{- end -}}
{{- end -}}

{{/*
Return the path to the CA cert file.
*/}}
{{- define "redis.tlsCACert" -}}
{{- if (include "redis.createTlsSecret" . ) -}}
    {{- printf "/opt/bitnami/redis/certs/%s" "ca.crt" -}}
{{- else }}
    {{- ternary "" (printf "/opt/bitnami/redis/certs/%s" .Values.kas.redis.tls.certCAFilename) (empty .Values.kas.redis.tls.certCAFilename) }}
{{- end -}}
{{- end -}}

{{/*
Return the path to the DH params file.
*/}}
{{- define "redis.tlsDHParams" -}}
{{- if .Values.kas.redis.tls.dhParamsFilename -}}
{{- printf "/opt/bitnami/redis/certs/%s" .Values.kas.redis.tls.dhParamsFilename -}}
{{- end -}}
{{- end -}}

{{/*
Create the name of the shared service account to use
*/}}
{{- define "redis.serviceAccountName" -}}
{{- if .Values.kas.redis.serviceAccount.create -}}
    {{ default (include "redis.fullname" .) .Values.kas.redis.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.kas.redis.serviceAccount.name }}
{{- end -}}
{{- end -}}

{{/*
Create the name of the master service account to use
*/}}
{{- define "redis.masterServiceAccountName" -}}
{{- if .Values.kas.redis.master.serviceAccount.create -}}
    {{ default (printf "%s-master" (include "redis.fullname" .)) .Values.kas.redis.master.serviceAccount.name }}
{{- else -}}
    {{- if .Values.kas.redis.serviceAccount.create -}}
        {{ template "redis.serviceAccountName" . }}
    {{- else -}}
        {{ default "default" .Values.kas.redis.master.serviceAccount.name }}
    {{- end -}}
{{- end -}}
{{- end -}}

{{/*
Return the configuration configmap name
*/}}
{{- define "redis.configmapName" -}}
{{- if .Values.kas.redis.existingConfigmap -}}
    {{- printf "%s" (tpl .Values.kas.redis.existingConfigmap $) -}}
{{- else -}}
    {{- printf "%s-configuration" (include "redis.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Return true if a configmap object should be created
*/}}
{{- define "redis.createConfigmap" -}}
{{- if empty .Values.kas.redis.existingConfigmap }}
    {{- true -}}
{{- end -}}
{{- end -}}

{{/*
Get the password secret.
*/}}
{{- define "redis.secretName" -}}
{{- if .Values.kas.redis.auth.existingSecret -}}
{{- printf "%s" (tpl .Values.kas.redis.auth.existingSecret $) -}}
{{- else -}}
{{- printf "%s" (include "redis.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Get the password key to be retrieved from Redis&reg; secret.
*/}}
{{- define "redis.secretPasswordKey" -}}
{{- if and .Values.kas.redis.auth.existingSecret .Values.kas.redis.auth.existingSecretPasswordKey -}}
{{- printf "%s" (tpl .Values.kas.redis.auth.existingSecretPasswordKey $) -}}
{{- else -}}
{{- printf "redis-password" -}}
{{- end -}}
{{- end -}}

{{/*
Return Redis&reg; password
*/}}
{{- define "redis.password" -}}
{{- if or .Values.kas.redis.auth.enabled .Values.kas.redis.global.redis.password -}}
    {{- $password_tmp := include "common.secrets.passwords.manage" (dict "secret" (include "redis.secretName" .) "key" (include "redis.secretPasswordKey" .) "providedValues" (list "kas.redis.global.redis.password" "kas.redis.auth.password") "length" 10 "skipB64enc" true "skipQuote" true "honorProvidedValues" true "context" $) -}}
    {{- $_ := set .Values.kas.redis.global.redis "password" $password_tmp -}}
    {{- .Values.kas.redis.global.redis.password -}}
{{- end }}
{{- end }}

{{/*
Returns the secret value if found or an empty string otherwise
Used for fetching Redis ACL user passwords from Kubernetes Secrets
*/}}
{{- define "common.secrets.get" -}}
{{- $secret := (lookup "v1" "Secret" .context.Release.Namespace .secret) -}}
{{- if and $secret (index $secret.data .key) -}}
    {{- index $secret.data .key | b64dec -}}
{{- else -}}
    {{- "" -}}
{{- end }}
{{- end }}

{{/*
Return standard labels without helm.sh/chart to prevent unnecessary
application restarts on chart version bumps.
*/}}
{{- define "redis.labels.withoutChartVersion" -}}
{{- $labels := include "common.labels.standard" ( dict "customLabels" .customLabels "context" .context ) | fromYaml -}}
{{- $_ := unset $labels "helm.sh/chart" -}}
{{- $labels | toYaml -}}
{{- end -}}

{{/* Define the suffix utilized for external-dns */}}
{{- define "redis.externalDNS.suffix" -}}
{{ printf "%s.%s" (include "redis.fullname" .) .Values.kas.redis.useExternalDNS.suffix }}
{{- end -}}

{{/* Compile all annotations utilized for external-dns */}}
{{- define "redis.externalDNS.annotations" -}}
{{- if and .Values.kas.redis.useExternalDNS.enabled .Values.kas.redis.useExternalDNS.annotationKey }}
{{ .Values.kas.redis.useExternalDNS.annotationKey }}hostname: {{ include "redis.externalDNS.suffix" . }}
{{- range $key, $val := .Values.kas.redis.useExternalDNS.additionalAnnotations }}
{{ $.Values.kas.redis.useExternalDNS.annotationKey }}{{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
{{- end }}
