apiVersion: deployments.plural.sh/v1alpha1
kind: Flow
metadata:
  labels:
    app.kubernetes.io/name: flow
    app.kubernetes.io/instance: flow-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: flow-sample
spec:
  name: test
  description: "test flow"
  bindings:
    read:
      - userEmail: marcin@plural.sh
    write:
      - userEmail: marcin@plural.sh
  workbenchAssociations:
    - workbenchRef:
        apiVersion: deployments.plural.sh/v1alpha1
        kind: Workbench
        name: flow-workbench-sample
        namespace: default
---
apiVersion: deployments.plural.sh/v1alpha1
kind: Workbench
metadata:
  labels:
    app.kubernetes.io/name: workbench
    app.kubernetes.io/instance: flow-workbench-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: flow-workbench-sample
  namespace: default
spec:
  name: flow-workbench-sample

