// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConsoleClientMock is an autogenerated mock type for the ConsoleClient type
type ConsoleClientMock struct {
	mock.Mock
}

type ConsoleClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsoleClientMock) EXPECT() *ConsoleClientMock_Expecter {
	return &ConsoleClientMock_Expecter{mock: &_m.Mock}
}

// NewConsoleClientMock creates a new instance of ConsoleClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsoleClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsoleClientMock {
	mock := &ConsoleClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
