import createIcon from './createIcon'

export default createIcon(({ size, color }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g clipPath="url(#clip0_6300_2543)">
      <path
        d="M5 5H11V11H5V5Z"
        fill={color}
        stroke={color}
        strokeLinejoin="round"
      />
      <path
        d="M2.5 2.5H13.5V13.5H2.5V2.5Z"
        stroke={color}
        strokeLinejoin="round"
      />
      <line
        y1="5"
        x2="3"
        y2="5"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="13"
        y1="5"
        x2="16"
        y2="5"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="5"
        y1="3"
        x2="5"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="5"
        y1="16"
        x2="5"
        y2="13"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="8"
        y1="3"
        x2="8"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="8"
        y1="16"
        x2="8"
        y2="13"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="11"
        y1="3"
        x2="11"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="11"
        y1="16"
        x2="11"
        y2="13"
        stroke={color}
        strokeWidth="2"
      />
      <line
        y1="8"
        x2="3"
        y2="8"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="13"
        y1="8"
        x2="16"
        y2="8"
        stroke={color}
        strokeWidth="2"
      />
      <line
        y1="11"
        x2="3"
        y2="11"
        stroke={color}
        strokeWidth="2"
      />
      <line
        x1="13"
        y1="11"
        x2="16"
        y2="11"
        stroke={color}
        strokeWidth="2"
      />
    </g>
  </svg>
))
