name: CI / Console UI

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/assets.yaml"
      - ".yarnrc.yml"
      - "assets/**"
      - "package.json"
      - "yarn.lock"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/assets.yaml"
      - ".yarnrc.yml"
      - "assets/**"
      - "package.json"
      - "yarn.lock"
jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: assets
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.11.1
      - run: yarn --immutable
      - run: yarn test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: assets
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.11.1
      - run: yarn --immutable
      - run: yarn lint
