name: Design system / Chromatic

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/chromatic.yml"
      - "js/.yarnrc.yml"
      - "js/design-system/**"
      - "js/package.json"
      - "js/yarn.lock"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/chromatic.yml"
      - "js/.yarnrc.yml"
      - "js/design-system/**"
      - "js/package.json"
      - "js/yarn.lock"

jobs:
  vouch:
    name: Vouch
    uses: ./.github/workflows/vouch-gate.yml
    permissions:
      contents: read

  chromatic:
    needs: [vouch]
    name: Publish Storybook
    if: ${{ github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: js
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.11.1
          cache: yarn
          cache-dependency-path: js/yarn.lock
      - run: corepack enable
      - run: yarn --immutable
      - run: yarn workspace @pluralsh/design-system build:storybook
      - uses: chromaui/action@6b3c2820222d23bad770d57a4ad5e2d1c91f92e9 # v18.9.5
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: js/design-system
          storybookBuildDir: storybook-static
          exitOnceUploaded: true
      - if: ${{ github.event_name == 'pull_request' && steps.chromatic.outcome == 'success' }}
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        with:
          header: storybook
          message: |
            **Storybook preview:** ${{ steps.chromatic.outputs.storybookUrl }}
