name: Validate Compatibility Schemas

on:
  pull_request:
    paths:
      - '.github/workflows/compatibility-schema-validation.yaml'
      - 'static/addons/**'
      - 'static/compatibilities/**'
      - 'static/compatibilities.yaml'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/compatibility-schema-validation.yaml'
      - 'static/addons/**'
      - 'static/compatibilities/**'
      - 'static/compatibilities.yaml'

permissions:
  contents: read

jobs:
  vouch:
    name: Vouch
    uses: ./.github/workflows/vouch-gate.yml
    permissions:
      contents: read

  validate-compatibility-schemas:
    needs: [vouch]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Validate add-on compatibility tables
        uses: dsanders11/json-schema-validate-action@f04ef3bca791388d2bd9ff3a50b27d1b2572158e # v2.1.0
        with:
          schema: static/compatibilities/schema.json
          files: |
            static/compatibilities.yaml
            static/compatibilities/*.yaml
          all-errors: true

      - name: Validate cloud add-on compatibility tables
        uses: dsanders11/json-schema-validate-action@f04ef3bca791388d2bd9ff3a50b27d1b2572158e # v2.1.0
        with:
          schema: static/addons/schema.json
          files: |
            static/addons/*.yaml
          all-errors: true
