name: CI / Datastore
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/datastore-ci.yaml"
      - "go/datastore/**"
      - "go/polly/**"
      - "go/client/**"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/datastore-ci.yaml"
      - "go/datastore/**"
      - "go/polly/**"
      - "go/client/**"
permissions:
  contents: read
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: go/datastore
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go/datastore/go.mod
          cache: true
      - name: Download dependencies
        run: go mod download
      - run: PATH=$PATH:$GOPATH/bin make build
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: go/datastore
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go/datastore/go.mod
          cache: true
      - name: Test
        run: PATH=$PATH:$GOPATH/bin make test
