name: CI / Go
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/go-ci.yaml"
      - "go/**"
      - "schema/**"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/go-ci.yaml"
      - "go/**"
      - "schema/**"
permissions:
  contents: read
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go/go.work
          check-latest: true
      - uses: golangci/golangci-lint-action@v7
        with:
          working-directory: go/
          version: latest
          automatic-module-directories: true
