name: CI / OCI Authentication Sidecar
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/oci-auth-ci.yaml"
      - "go/oci-auth/**"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/oci-auth-ci.yaml"
      - "go/oci-auth/**"
permissions:
  contents: read
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: go/oci-auth
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go/oci-auth/go.mod
          cache: true
      - run: go mod download
      - run: PATH=$PATH:$GOPATH/bin make build
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: go/oci-auth
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go/oci-auth/go.mod
          cache: true
      - run: go mod download
      - run: PATH=$PATH:$GOPATH/bin make test
